### ISSUE TITLE
Adaptar o app para o iPad Pro de 10,5"

### ISSUE THREAD

**Issue by eduardomarqu-es** [MacMagazine/app-iOS#100]
Precisamos adaptar o app para a nova tela de 10,5" do iPad Pro ou isso é algo feito de forma automática?

**Comment by Themakew** [comment]
@eduardomarqu-es O autolayout deveria cuidar disso sozinho.

**Comment by rfischmann** [comment]
Tem como só verificarem se está tudo beleza, pelo Simulator? Imagino que não precise mesmo de nada.

**Comment by Themakew** [comment]
Rodei aqui e tudo beleza, só um bug que encontrei referente ao meu pull request de layout no iPad😓

**Comment by kazziosoftware** [comment]
Acho q esse issue já pode ser encerrado. Confere?

**Comment by rfischmann** [comment]
Acho que sim.
