### ISSUE TITLE
Adotar sistema de review da App Store?

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#101]
O que acham de implementarmos a nova API nativa de reviews da App Store?

É bem bacaninha e não-intrusiva. Acho importante lembrar usuários de avaliarem o app, muitos esquecem completamente disso.

**Comment by Themakew** [comment]
@rfischmann Feito.

**Comment by rfischmann** [comment]
Caraca, rápido assim?! 😮

**Comment by Themakew** [comment]
2 linhas de código 🤗

**Comment by Themakew** [comment]
O gerenciamento é todo feito pelo framework, necessitando só chamar o mesmo. 🤔

**Comment by rfischmann** [comment]
Hahaha animal!

**Comment by Themakew** [comment]
Mas para me deixar com fios brancos a implementação não esta funcionando como esperado... Terei que investigar 🤔

**Comment by rfischmann** [comment]
Sem pressa.

**Comment by rfischmann** [comment]
Está na versão 3.1.3, só não vi funcionando ainda.

**Comment by Themakew** [comment]
Talvez precise de uma refatoração, tinha colocado para disparar a cada 50 vezes que a pessoa abrisse o app. @kazziosoftware leve em consideração isso quando estiver passando para swift.
