### ISSUE TITLE
Compatibilidade para o  Watch

### ISSUE THREAD

**Issue by Themakew** [MacMagazine/app-iOS#103]
Vi muitos reviews na App Store de pessoas pedindo a compatibilidade para o  Watch. Sendo assim abro essa issue para discussão do que poderia ser feito e se faz sentido fazer algo mesmo.

Por mim, do que tenho visto na store de apps semelhando ao do MM, o que tem para  Watch é basicamente um feed de posts e o usuário podendo colocar o posts marcado para ler posteriormente no iPhone, algo bem simples e que deve ser desse jeito mesmo para o Watch. Acho que essa issue poderia se associar a issue #50, podendo visualizar a lista de posts favoritos.

Então fica aberto a discussão. 😊

**Comment by rfischmann** [comment]
Acho um bom caminho, @Themakew.

Outra possibilidade seria realmente de implementar uma versão "mini" do app no Watch, só com texto (tanto da lista de posts quanto da leitura dos artigos em si). Só que a experiência deve ser bem ruim, né…

**Comment by brunoteixeiralc** [comment]
Eu também acho que ficaria muito ruim ver o texto no watch. Caso eu tivesse um Watch , eu não ficaria vendo os artigos nele. O interessante seria somente uma notificação quando tem algo novo no site. (Não sei se já essa funcionalidade integrado no watch rsrsts)

**Comment by rfischmann** [comment]
Sim, a notificação em si já chega via iPhone na boa.

Mas acreditem: especialmente no Apple Watch Series 4, com a tela maior, não é tão ruim assim ler textos no relógio. Não é à toa que a Apple implementou o WebKit no watchOS.

**Comment by brunoteixeiralc** [comment]
Entendi...posso tentar fazer um app do watch então e a gente faz uns testes de usabilidade.

**Comment by kazziosoftware** [comment]
Feito na versão 4.0

**Comment by michelmelo** [comment]
tem alguma limitação das versão do apple Watch? o meu é o da primeira geração, e nao aparece no relogio.

**Comment by rfischmann** [comment]
@michelmelo Imagino que use o WebKit, então o requerimento mínimo deve ser o watchOS 5. O Apple Watch de primeira geração só vai até o watchOS 4.

**Comment by michelmelo** [comment]
ok, deve ser isso.

**Comment by kazziosoftware** [comment]
Correto, a versão mínima para watchOS é 5.
