### ISSUE TITLE
Bug de layout no iOS 11

### ISSUE THREAD

**Issue by Themakew** [MacMagazine/app-iOS#104]
Bug na logo na parte de cima quando o app é aberto:
![img_9e472f197618-1](https://user-images.githubusercontent.com/3030029/30616228-f6c55c94-9d67-11e7-86d9-778c46f1c542.jpeg)

**Comment by Themakew** [comment]
Bug na webview, o frame está maior e esta ficando atrás da navigation controller, fazendo com que parte do conteúdo esteja cortado:
![54baf04e-d3b5-47be-a5d8-9e6b3b3505c8](https://user-images.githubusercontent.com/3030029/30947798-20d45a78-a3e2-11e7-8a72-ff27ed137974.png)

**Comment by rfischmann** [comment]
Vamos soltar um update nos próximos dias corrigindo isso, valeu!

**Comment by rfischmann** [comment]
Precisamos corrigir isso ASAP, pessoal. @kazziosoftware?

**Comment by kazziosoftware** [comment]
@rfischmann olharei isso até o final da semana.

**Comment by kazziosoftware** [comment]
Resolvido em 3.1.4
