### ISSUE TITLE
Sugestão: easter egg

### ISSUE THREAD

**Issue by lucascaton** [MacMagazine/app-iOS#107]
Seria massa ter um _easter egg_, algo como:

Tocar 3x no logo para aparecer uma mini-página com a história do MacMagazine 😄

**Comment by rfischmann** [comment]
Eu gosto da ideia.

**Comment by Morbix** [comment]
Essa mini-página tem disponível hoje ou ele poderia apontar para cá: https://macmagazine.com.br/sobre/

**Comment by brunoteixeiralc** [comment]
Então poderia deixar desse jeito:
3 cliques na logo abriria uma WebView redirecionando para : https://macmagazine.com.br/sobre/ ?

**Comment by rfischmann** [comment]
Pode ser. Três toques bem rápidos, certo?

**Comment by brunoteixeiralc** [comment]
Blz..vou implementar essa issue.

**Comment by rfischmann** [comment]
Ainda acho válido.

**Comment by rfischmann** [comment]
Implementado na 4.1, hehe!
