### ISSUE TITLE
Bug no iPhone X

### ISSUE THREAD

**Issue by Themakew** [MacMagazine/app-iOS#109]
Ocorre quando se fecha um video fullscreen no iPhone que ficou em landscape, daí quando retorna para o app ocorre esse bug:
 
![simulator screen shot - iphone x - 2017-10-05 at 14 47 07](https://user-images.githubusercontent.com/3030029/31242272-dafea9b2-a9dc-11e7-8969-1236b13d41b1.png)

![simulator screen shot - iphone x - 2017-10-05 at 14 47 15](https://user-images.githubusercontent.com/3030029/31242270-dad0f58a-a9dc-11e7-9775-d0758d297eb5.png)

**Comment by brunodlz** [comment]
Tentei simular o seu caso e não ocorreu comigo. Na próxima vez, tenta criar um gif ao invés de enviar prints com este bug e reportar aqui novamente :)

**Comment by Themakew** [comment]
@brunodlz o bug ja foi corrigo, por isso que você não viu.
