### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by Themakew** [MacMagazine/app-iOS#110]
@kazziosoftware enumere as US que você fez para passar o código para swift e no commit da implementação da US coloque o número correspondente. Fica melhor para fazer o tracking das US`s com os commits.

**Comment by Themakew** [comment]
Assim como das tarefas também, é sempre bom fazer o tracking das US com as tarefas e ao commitar colocar a tarefa ou/e US correspondente.

**Comment by kazziosoftware** [comment]
@Themakew sim, ainda estava preparando o esqueleto do projeto. não consegui avançar com a velocidade que esperava, por isso algumas coisas foram feitas sem identificar as User Stories, inclusive Projects ainda está em desenvolvimento.
Obrigado.

**Comment by Themakew** [comment]
@kazziosoftware ok, sem problemas.
