### ISSUE TITLE
Crash ao salvar imagem

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#113]
Relato de leitor:

=================================
iOS 11.2 - iPhone 6S Plus

Video exemplificando:

https://1drv.ms/v/s!AkcDNlgNzNdOgZ0LpWgQ9XAsNSYRUQ

--
Mensagem enviada pelo formulário de contato do MacMagazine.

De: Lucas de Oliveira Leite <loliveira2879@gmail.com>
Data/hora: 14/11/2017 às 03:03
IP: 189.121.75.20
User-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_2 like Mac OS X) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0 Mobile/15C5107a Safari/604.1
=================================

Testei aqui no iPhone X com o iOS 11.1.1 e rola o _crash_ também.

**Comment by kazziosoftware** [comment]
Resolvido em 3.1.4.
