### ISSUE TITLE
Problema de usabilidade e funcionalidade

### ISSUE THREAD

**Issue by Themakew** [MacMagazine/app-iOS#121]
Os botões que possibilitam navegar pelos posts, aqueles da parte superior direita, ficaram muito juntos o que prejudicou a sua usabilidade na hora de ativá-los. Outro problema é quanto a a ativação da funcionalidade dos botões, pelo menos aqui nos meus testes, tive que tentar várias vezes para que fosse para o post anterior ou para o próximo. Teve alguma mudança nessa última versão que trouxe todos esses problemas.

**Comment by Themakew** [comment]
Outro bug relacionado:

<img width="768" alt="screen shot 2017-12-12 at 17 45 45" src="https://user-images.githubusercontent.com/3030029/33905029-6a5389c2-df64-11e7-9974-efc632f6d28d.png">

**Comment by kazziosoftware** [comment]
arrumado na v 3.1.5

**Comment by rfischmann** [comment]
Valeu pelo feedback, @Themakew!

**Comment by kazziosoftware** [comment]
@rfischmann acho que esse issue já foi resolvido, certo?

**Comment by rfischmann** [comment]
Corrigido na versão 3.2, prestes a ser lançada.
