### ISSUE TITLE
Bug ao compartilhar copiando link

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#124]
Relato de leitor:

> Olá Srs...bom dia.
> Uso com frequência o APP do MacMagazine no meu iphone e qdo desejo enviar uma reportagem para alguém, por whatszap ou messenger, as vezes uso a função COPIAR LINK que é aberta no menu de compartilhamento da msg.
> 
> O que ocorre é que o link para COLAR, acaba vindo com o texto da reportagem junto do link iniciado em 'https'....e ai a pessoa que recebe, não consegue abrir de imediato.
> 
> A solução, após COPIAR o link e colar no app de mensagem, eu acabo inserindo um ´espaço´ manualmente entre o texto e o link, e tudo funciona normal.
> 
> É besteira, entendo...mas achei que deveria compartilhar com vocês.
> 
> abraço
> Fabio Santos
> 
> --
> Mensagem enviada pelo formulário de contato do MacMagazine.
> 
> De: Fabio Santos <fabiohrs@me.com>
> Data/hora: 29/01/2018 às 11:16
> IP: 201.83.98.75
> User-agent: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

Consegui reproduzir aqui:

1. Abra uma matéria;
2. Toque no menu de compartilhar;
3. Escolha "Copiar";
4. Vá ao WhatsApp e abra uma conversa;
5. Cole.

Vai o título da matéria colado com a URL dela.

**Comment by rfischmann** [comment]
Esse bug ainda persiste na 3.2, acabei de testar. Fica pro próximo update.

**Comment by kazziosoftware** [comment]
@rfischmann no iOS 12 isso não acontece. Será q vc consegue validar?

**Comment by rfischmann** [comment]
Parece ok, mesmo. Que coisa.

**Comment by brunoteixeiralc** [comment]
Está OK mesmo. Estou usando a versão 3.2.1

**Comment by rfischmann** [comment]
Fechando isso, então!
