### ISSUE TITLE
Bug ao fazer Peek (3D Touch) na lista de posts

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#133]
_Report_ recebido via Facebook:

> **Alan Henrique Pégoli**
> 
> Olá, MacMagazine! Encontrei um bug no App de vocês quando se usa o peek do 3DTouch. Imagino que já tenham conhecimento que ao pressionar sobre um artigo na lista de artigos, a TableView inteira está vindo pra frente, ao invés de só a célula do artigo. É um bug relativamente simples de arrumar...

**Comment by leonardorock** [comment]
Fiz um pull request pra resolver esse bug, se puderem testar ficarei grato ;)

https://github.com/MacMagazine/app-iOS/pull/138
