### ISSUE TITLE
Cache do app precisa ser atualizado

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#134]
É **muito** comum nós mexermos em posts já publicados no site, seja para corrigir alguma besteira no texto ou até para fazer uma atualização de fato no artigo com novas informações.

O problema é que o cache local do app não é atualizado de acordo com a limpeza de cache do nosso site, e aí os posts ficam sempre desatualizados para quem já os abriu no iGadget.

Como resolver isso? Alguma forma de "informarmos" ao app para limpar seu cache? Fazer isso automaticamente, de tempos em tempos? Ou simplesmente abandonamos o cache de posts no app, deixando apenas da lista inicial?

Ideias?

**Comment by kazziosoftware** [comment]
voto por não manter cache ou qq tipo de armazenamento no App.

**Comment by rfischmann** [comment]
Da tela inicial é importante ter, nem que seja um cache básico.

**Comment by RaphaelPrata** [comment]
Acho que não mater cache nenhum pode prejudicar a experiência do usuário se o sinal da operadora cair por exemplo quando ele estiver acessando o app.

**Comment by rfischmann** [comment]
Talvez o jeito seja manter o cache, mas encurtar o seu tempo de armazenamento. Tipo, limpar a cada 12h?

**Comment by RaphaelPrata** [comment]
Sim. Não sei se é possível mas se tivesse como limpar o cache só da notícia que foi atualizada seria interessante.

**Comment by rfischmann** [comment]
Possível é, mas acho que complica. Teria que haver algum tipo de integração com o nosso WordPress, de forma que, ao atualizarmos um post no site, ele se comunicasse com o servidor do app mandando o cache daquele post ser apagado em todos os dispositivos.

**Comment by gustavogervasio** [comment]
Este cache é na home do aplicativo, listagem de posts?

**Comment by rfischmann** [comment]
Não, dos posts em si mesmo.

**Comment by gustavogervasio** [comment]
Então não entendi o problema, já que a tela de detalhe do post é um webview.

**Comment by rfischmann** [comment]
Até onde eu sei, o app tem um cache interno dessas web views.

**Comment by gustavogervasio** [comment]
Entendi, vcs usam a política de cache: `ReturnCacheDataElseLoad`
https://developer.apple.com/documentation/foundation/nsurlrequest/cachepolicy

Eu não usaria essa política aí, acho que para este tipo conteúdo eu usaria: 

`reloadIgnoringLocalCacheData `

**Comment by gustavogervasio** [comment]
ou esta política: 

https://developer.apple.com/documentation/foundation/nsurlrequest/cachepolicy/useprotocolcachepolicy

**Comment by gustavogervasio** [comment]
Criei um pull request, se fizer sentido para vocês:

https://github.com/MacMagazine/app-iOS/pull/141

**Comment by rfischmann** [comment]
@gustavogervasio Mas aí você está simplesmente eliminando o cache local, que prejudica a experiência de uso do app. O ideal era ele ter cache, sim, mas detectar se a URL de origem foi atualizada e, nesse caso, carregar a nova versão.

**Comment by gustavogervasio** [comment]
Eu nunca usei em meus projetos, mas talvez tenha que testar a política de cache `useProtocolCachePolicy`.

**Comment by rfischmann** [comment]
Olhando o link que você mandou, a política que mais faz sentido nesse caso que descrevi é a `reloadRevalidatingCacheData`, não?

**Comment by gustavogervasio** [comment]
Infelizmente de acordo com a documentação essa política não deve ser usada.

https://developer.apple.com/documentation/foundation/nsurlrequest/cachepolicy/reloadrevalidatingcachedata

**Comment by rfischmann** [comment]
Que pena.

**Comment by gustavogervasio** [comment]
@rfischmann pensei em uma solução:
https://github.com/MacMagazine/app-iOS/pull/142

Toda vez que o no título do post tiver a palavra `atualizado` eu mando desconsiderar o cache local e busco as informações.

**Comment by rfischmann** [comment]
Boa, @gustavogervasio! Obrigado.

Não resolve totalmente o problema, porque às vezes só corrigimos alguma coisa no post mesmo sem incluir uma atualização de fato no fim, mas já ajuda demais. 👏🏼

**Comment by michelmelo** [comment]
Olá uma sugestão é ir pela data do update, se na api tiver isso.

**Comment by kazziosoftware** [comment]
Feito na versão 4.0
