### ISSUE TITLE
Sugestão: StoreKit API - Rate

### ISSUE THREAD

**Issue by brunoteixeiralc** [MacMagazine/app-iOS#136]
Boa noite.
Isso seria considerado uma nova feature. Que iria ajudar ao MacMagazine ser avaliado mais vezes.
Utilizando essa API da Apple , em algum momento do aplicativo irá abrir uma dialog para o usuário avaliar o app. **Obs: Irá aparecer no máximo 3 vezes durante 365 dias**.

Segue o link: https://developer.apple.com/app-store/ratings-and-reviews/

Por exemplo:
<img width="431" alt="captura de tela 2018-04-26 as 22 33 57" src="https://user-images.githubusercontent.com/767993/39340008-f5c470dc-49a1-11e8-92b8-85676bd81e94.png">

**Comment by rfischmann** [comment]
Tenho quase certeza de que nosso app já tem isso… alguém confirma?

**Comment by brunoteixeiralc** [comment]
Show @Themakew !

**Comment by kazziosoftware** [comment]
@rfischmann pode fechar esse ticket pq já está implementado

**Comment by rfischmann** [comment]
Ok!
