### ISSUE TITLE
Número de notícias no aplicativo

### ISSUE THREAD

**Issue by brunoteixeiralc** [MacMagazine/app-iOS#139]
Percebi que nessa nova versão, caso queira ver uma notícia de 2 dias atrás, não consigo. Parece que somente aparece notícias de hoje e algumas de ontem. Isso seria uma issue? Ou o fluxo normal é esse?

**Comment by kazziosoftware** [comment]
@rfischmann esse issue pode ser finalizado já q foi corrigido na última release.

**Comment by rfischmann** [comment]
De fato.
