### ISSUE TITLE
Comentários difíceis de ler no Modo Escuro

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#140]
Oi pessoal,

Preciso da ajuda de vocês para vermos se conseguimos melhorar os comentários do Disqus no nosso Modo Escuro.

Ocorre que não temos como passar um parâmetro de Modo Escuro pro Disqus em si. Ele se baseia na cor de fundo definida no CSS do site para o `<body>` e, a partir daí, define se sua fonte será clara ou escura.

Para o Modo Escuro do nosso app, nós chamamos um arquivo CSS externo que altera as cores padrão do site para o Modo Escuro. O problema é que nem sempre "dá tempo" (não sei bem o que rola) de o Disqus detectar isso e carregar corretamente no app, com as fontes claras.

Alguém tem alguma ideia de como podemos melhorar isso e resolver o problema em definitivo?

**Comment by cassio-rossi** [comment]
@rfischmann acho q esse issue já pode ser encerrado, correto?

**Comment by rfischmann** [comment]
Ainda recebi um ou outro relato de que o problema não foi resolvido 100%, mas realmente agora é raro não abrir certo. Vou fechar.
