### ISSUE TITLE
Melhorias de acessibilidade

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#144]
Um usuário do app, que é cego, reclamou que o botão de menu não está etiquetado.

> Caro Rafael. Sou cego. Com o leitor de ecrã o botão da aplicação é lido como botão, em vez de dizer menu. Isto é porque o botão não está etiquetado.

Isso é fácil de arrumar?

**Comment by Themakew** [comment]
@rfischmann não é complicado de fazer não, verifiquei que mesmo na versão 4.0, muitas coisas são lidas somente como botão. Vou fazer essa melhoria e submeto um pull request.

**Comment by rfischmann** [comment]
Show, valeu @Themakew!

**Comment by kazziosoftware** [comment]
Muito bom. Vamos continuar trabalhando nesse assunto que está quase lá.

**Comment by eduardomarqu-es** [comment]
Mais um feedback do nosso leitor cego:

> Olá Eduardo, bom dia! Obrigado por reportar a minha sugestão, mudou o aplicativo e os botões que citei agora estão etiquetados. Inclusive ouvi o Breno mencionar o meu nome no último podcast, rsrs. Um detalhe apenas. Não precisa que a etiqueta mencione poste favorito, basta apenas favorito, nem poste compartilhar, apenas a palavra compartilhar.

**Comment by Themakew** [comment]
@eduardomarqu-es interessante, como não temos costume e nem idéia de como é a melhor forma de utilizar esse recurso.

**Comment by Themakew** [comment]
O novo recurso de accessibilidade lançado pela apple pode ser interessante de ver se é necessário adaptar algo no app para funcionar.

**Comment by rfischmann** [comment]
@Themakew Sim, esse novo controle de voz é fenomenal.
