### ISSUE TITLE
Erro ao compartilhar posts pro Twitter

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#145]
Relato do problema:

> Acompanho as matéria que fazem com bastante gosto pela qualidade e empenho de vocês e por conta disso gostaria de colaborar com a indicação de um problema que tem ocorrido após a nova versão do app para iOS.
> 
> Toda vez que publicam uma matéria interessante e que compartilho pelo meu Twitter como antes, agora a opção de share só envia a imagem e a headline da matéria, sem o link da mesma embutido ou não na imagem.

Confirmei aqui. Ao compartilhar pro Twitter, só vai o título do post e a imagem destacada — sem a URL dele.

Precisamos arrumar, é importante.

**Comment by kazziosoftware** [comment]
Feito na versão 4.0
