### ISSUE TITLE
App dando Crash

### ISSUE THREAD

**Issue by Themakew** [MacMagazine/app-iOS#156]
Limpei a cache do app e fui navegar pela aba de videos, não carregou mas nenhum video e ficou aparecendo a mensagem de que eu não tinha favoritado nada ainda. Depois disso o app deu crash e agora não abre mais, fora que a navegação dessa parte dos videos está bem lenta, pois o scrool fica dando vários travamentos. Testei no ipad air 2 e esse problema ocorreu.

Update: desinstalei o app e fiz o mesmo procedimento, e o erro voltou a ocorrer.

**Comment by kazziosoftware** [comment]
Foi corrigido o problema de não recarregar os videos após a limpeza do cache e o texto informativo.
