### ISSUE TITLE
Bug na splitview dos posts

### ISSUE THREAD

**Issue by Themakew** [MacMagazine/app-iOS#159]
Se tem um bug na passagem de posts via no ipad, o tracking do novo post carregado, na tableview à esquerda, não acompanha a passagem de posts como mostrado abaixo:

![BFF5403A-6028-4A4A-9803-DC900AAD81A4](https://user-images.githubusercontent.com/3030029/58446916-fbf5ec00-80d8-11e9-9643-f6949d1e358f.png)

**Comment by kazziosoftware** [comment]
Tentei reproduzir mas não consegui. Poderia detalhar mais o passo-a-passo do problema para eu tentar reproduzir aqui? Obrigado.

**Comment by Themakew** [comment]
@kazziosoftware Na tela de posts, vá passando de posts pelo swipe da detail view. Na master você verá que o tracking (a parte cinza no primeiro post da foto) da o tableview não acompanhará os posts que estão da detail view atualmente

**Comment by kazziosoftware** [comment]
Entendi agora. Vou ver isso. Obrigado
