### ISSUE TITLE
Assinatura para tirar propagandas

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#162]
Sugestão de usuário:

> Olá. 
> Não é um problema, mas uma sugestão.
> 
> O app anterior era ruim demais (rsrs) essa nova versão está espetacular, está melhor acessar os posts pelo app do que pelo site. Estão de parabéns.
> 
> Minha sugestão é que vocês façam uma assinatura do app para quem quiser retirar as propagandas, seria possível?
> Eu pagaria uma anuidade num valor razoável para ter o app “limpo” de anúncios e poder curtir a fluidez que essa nova versão trouxe para ele.
> 
> Abraços. 
> 
> Fabio Gimenez Eleuterio

**Comment by Themakew** [comment]
@rfischmann Acredito que essa feature tenha que ser implementada primeiro no sistema web, para depois ter alguma adaptação no app.

**Comment by rfischmann** [comment]
@Themakew Me parece infinitamente mais simples de começar pelo app. Sistema de pagamentos da Apple, usamos o mesmo esquema baseado em user-agent do Modo Escuro e dos tamanhos de fontes para esconder as propagandas — não precisa de login no nosso WordPress nem nada…

**Comment by rfischmann** [comment]
Que tal implementarmos isso na 4.2?

**Comment by rfischmann** [comment]
A versão 4.2 terá login para patrões, já é um começo.

Num próximo update, podemos oferecer isso como compra interna também mesmo para quem não é patrão poder usar o app sem banners.

**Comment by rfischmann** [comment]
Por mim, isso entra na 4.3. Já está quase tudo pronto.

**Comment by rfischmann** [comment]
Estará na 4.4.
