### ISSUE TITLE
Aprimoramentos no Modo Escuro

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#163]
Email de usuário:

> Boa noite.
> 
> Como leitor do MacMagazine, 100% pelo app, e AMANTE do modo escuro gostaria de sugerir o modo escuro “automático” para o app. Iria ser algo incrível!
> No mais, parabéns pelo ótimo aplicativo.
> 
> Att,
> Tomás Batistone
> Técnico em Publicidade
> Tel.: (21) 9 9698-5486

A primeira coisa que teremos que fazer, pro iOS 13, é fazer o app responder ao Modo Escuro nativo do sistema automaticamente.

Mas também é legal permitir que o usuário defina isso manualmente se quiser (usar o app claro com o sistema escuro ou vice-versa), e a ideia do Tomás é uma boa por exemplo para ele só ficar escuro em determinada hora do dia ou quem sabe de acordo com o nível de brilho da tela — o Tweetbot tem esse recurso.

**Comment by Themakew** [comment]
Eu acrescentaria as thumbnails da aba de podcasts e videos quando não carregaram as imagens ainda, que ficam brancas antes de mostrar a imagens correspondente. Acredito que poderia ser uma imagem mais escura para não disparar um brilho muito forte nas vistas do usuário.

**Comment by Themakew** [comment]
Outro aprimoramento sugerido por um leitor:

> Pessoal, app tá incrível! Trabalho muito bem feito.
Tenho só uma observação/pedido, mudem o splash do app pra ficar mais em acordo com o dark mode. 
Dá aquele “choque” abrir o app e vir a imagem branca com a logo, antes de carregar a interface escura...
E parabéns pelo trabalho!

**Comment by kazziosoftware** [comment]
Não é possível alterar o Splash screen

**Comment by rfischmann** [comment]
Não mesmo, @kazziosoftware?! 😕

**Comment by Themakew** [comment]
Quanto a splash screen nunca vi mesmo uma forma de mudar dinamicamente, tanto que o app do youtube tem o mesmo comportamento do macmagazine, abre aquela tela super branca mesmo com o app em dark mode.

**Comment by eduardomarqu-es** [comment]
Eita, verdade. Aqui fica com essa tela branca também. Que coisa…

**Comment by kazziosoftware** [comment]
A mudança para Dark mode nativo não será trivial - não será difícil, mas não será trivial. Ainda bem q temos meses pela frente.

**Comment by Themakew** [comment]
@kazziosoftware você está rodando os betas? vai implementar as novas mudanças até setembro?

**Comment by kazziosoftware** [comment]
Nunca se sabe ... LOL
