### ISSUE TITLE
Não é possível favoritar posts nos resultados de buscas

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#164]
Relato de usuário:

> Bom dia 
> 
> Gostaria de fazer uma ponderação sobre um recurso presente no novo app de vcs.
> 
> O recurso de favoritar as matérias não está funcionando após pesquisar pela mesma no campo de busca.
> 
> Sendo a matéria aberta diretamente no feed inicial, sem problema. O recurso funciona perfeitamente. 
> 
> Independente desse detalhe, parabéns a toda a equipe pela atualização. Ficou ótimo! 
> 
> 👏🏼👏🏼👏🏼

**Comment by kazziosoftware** [comment]
Isso não é bug, foi feito assim mesmo, pois a busca é online, não fica salva
Para favoritar, precisaria salvar.
Posso pensar em como fazer.

**Comment by rfischmann** [comment]
Se for possível fazer funcionar, acho interessante. É um cenário que faz bastante sentido, o cara buscar algo e salvar um ou mais posts para ler depois.

**Comment by kazziosoftware** [comment]
@rfischmann vc poderia mudar a tag para Feature, pois não é um bug de fato. Obrigado.

**Comment by rfischmann** [comment]
Ainda falta fazer funcionar com o atalho de deslizar na própria lista de resultados.
