### ISSUE TITLE
Selecionar o primeiro post ao abrir o app

### ISSUE THREAD

**Issue by Themakew** [MacMagazine/app-iOS#165]
Acredito que o comportamento do app que tinha antes, o de abrir o app e selecionar o post mais atual, deveria voltar. Por vezes tenho rolar bastante a tela de posts para ir aos mais atuais, o que acham?

**Comment by kazziosoftware** [comment]
O comportamento é o mesmo, no iPad fica memorizado o ultimo post visto, logo, ao abrir o App, volta para esse mesmo post

**Comment by Themakew** [comment]
@kazziosoftware eu mesmo programei isso na outa versão, era selecionado o post mais recente ao abrir o app, acho que ficava melhor assim.

**Comment by kazziosoftware** [comment]
Eu tbém prefiro abrir o post mais recente, mas segui o que estava na última versão do App, corrigindo os problemas q tinha, mas sem alterar a funcionalidade. Fica a critério do @rfischmann o que fazer.
Tirar essa "característica", é moleza.

**Comment by Themakew** [comment]
@kazziosoftware não está como na ultima versão como comentei. O comportamento de antes era ao abrir o app da primeira vez, o post mais recente era selecionado. Depois de aberto o app, estando em backgroud, aí sim funcionava como está agora :)

**Comment by rfischmann** [comment]
Eu sinceramente não sei o que é melhor. Acho que tem que ser o que faz mais sentido, isto é, o que o usuário espera que aconteça quando abre o app. Inputs?

**Comment by Themakew** [comment]
@rfischmann a experiência que tenho as vezes é de abrir o app, depois de alguns dias sem abrir, e ter que dar scroll até o topo para ver os posts mais atuais. Eu particularmente gostaria de ver o que tem mais atual e ir dando scroll para posts mais antigos.

**Comment by kazziosoftware** [comment]
Eu tbém prefiro ler os mais atuais sempre
Podemos deixar a opção de ver o último somente pelo 3D Touch - q irá morrer e que não funciona no iPad, logo, melhor tirar ;)

**Comment by kazziosoftware** [comment]
@Themakew faz tempo q isso mudou mas acho que tinha uma opção de só memorizar por alguns dias/horas. Ai sim faz sentido. Sempre é bom explicar tudo com o mínimo detalhe para os outros entenderem.
Anyway, eu, pessoalmente, prefiro sem.

**Comment by Themakew** [comment]
> Eu tbém prefiro ler os mais atuais sempre
> Podemos deixar a opção de ver o último somente pelo 3D Touch - q irá morrer e que não funciona no iPad, logo, melhor tirar ;)

Provavelmente eles irão substituir o 3d touch pelo toque longo e todos os dispositivos terão os previews dos apps, mas vale ficar atento a esses mudanças do iOS 13.

**Comment by rfischmann** [comment]
Eu gosto muito da ideia de só lembrar por dias/horas, mas se não é possível concordo que o melhor comportamento seja o de mostrar logo os mais atuais.

E sim, como o @Themakew falou, o 3D Touch deverá ser substituído pelo Haptic Feedback e vai rolar em todos os devices.

**Comment by kazziosoftware** [comment]
Então, mas não dá para ficar indo e vindo. Ou espera para ver e muda de uma única vez, ou tira agora

**Comment by rfischmann** [comment]
Tirar os atalhos do ícone não faz sentido, mas qual o problema de alterar o comportamento da rolagem desde já?

**Comment by kazziosoftware** [comment]
Quanto tempo? 24h?

**Comment by rfischmann** [comment]
Acho excelente.
