### ISSUE TITLE
Versão pro tvOS?

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#171]
Sugestão nos comentários do site:

> **Luiz Assis** 8 hours ago
> Poderia ter a aba do conteúdo, de vídeos, podcasts é uma de buscar
> 
> O conteúdo em si adaptado para TV, seria parecido com o Twitter ou o próprio app MacMagazine em modo paisagem. Uma grande imagem/coluna de um lado com o resumo/título e do outro a meteria escrita.

**Comment by gcmms** [comment]
Gostaria de desenvolver essa feature ao APP,  basta clonar ele na maquina desenvolver e fazer um PR?

**Comment by rfischmann** [comment]
Desculpe a demora, @gcmms! Que bacana que você quer tocar isso, obrigado. 😊

Eu acho que é desse jeito que você falou, sim, mas o @cassio-rossi certamente pode lhe orientar melhor do que eu sobre isso.

**Comment by cassio-rossi** [comment]
Olá @gcmms. Obrigado por querer colaborar com nosso projeto.
Os passos para desenvolver uma nova feature são:
1) Clone o repo e crie uma nova branch. Nesse caso, pode ser feature/tvOS
2) Faça a implementação - veja no readme as orientações sobre code style, formato, regras para utilização de gerenciadores de dependência e outras dicas importantes.
3) Uma vez finalizado o desenvolvimento, crie um Pull Request e aguarde nossos comentários e aprovação.
Estou a disposição para esclarecimentos adicionais, ajuda no desenvolvimento e demais orientações.
Também tenho algumas ideias do que fazer na versão tvOS. Você também pode me contatar pelo Telegram (@cassiorossi)

**Comment by gcmms** [comment]
Uhm que legal @cassio-rossi quero contribuir sim , logo vou te chamar no telegram para conversar sobre suas ideias

**Comment by cassio-rossi** [comment]
Olá @gcmms tudo bom? Vamos conversar via Telegram? Se não tiver esse App, me avisa outra forma. Estamos reformulando o App e temos grandes planos para o iOS/tvOS 14 e seria legal já começarmos a conversar. Temos tempo, mas estou reformulando todo o sistema, modernizando, modularizando e isso terá um impacto no projeto. Aguardo seu contato. (meu Telegram é @cassiorossi)

**Comment by cassio-rossi** [comment]
@rfischmann apesar da idéia ser boa, estive fazendo uns estudos e vi que:
1) o tvOS não tem uma web view
2) isso quer dizer que não é possível reproduzir videos do YouTube, que seria o principal atrativo do App
3) se procurar alternativas, verá que violam as regras do Google

Será que ainda assim vale a pena ter uma versão para tvOS?

**Comment by rfischmann** [comment]
Nossa, o YouTube não tem nenhuma API própria para isso? 😧

**Comment by gcmms** [comment]
Penso que podemos consumir a API do youtube para pegar as informações do canal do MM, e se n conseguir trazer o video para dentro do app. Podemos chamar o video pelo proprio app do youtube.

Muito embora o uso de WebView na Apple TV seja algo não muito legal, poderíamos arriscar um piloto com esta lib (https://developers.google.com/youtube/v3/guides/ios_youtube_helper)e submeter ele ao review da apple . Eu entendo que eles peguem pessoas que usem a apple tv como um "navegador " usando o app 100% em html5 em tela cheia

**Comment by cassio-rossi** [comment]
Não, o YouTube não tem API para isso e, por não existir Webview no tvOS não é possível usar esse exemplo e também não acho legal direcionar o usuário para o App YouTube, até porque, basta ele assinar o canal MM e ir direto, sem a necessidade de ser redirecionado. Como UX não acho legal, como usuário não vejo benefícios e como técnico, não vejo solução, infelizmente.

**Comment by rfischmann** [comment]
É, as duas coisas que eu acho que seria legal nosso app para tvOS ter seria uma aba com vídeos (contanto que pudessem ser vistos dentro do app) e outra com podcasts.

Se não tem API para isso, mata a ideia.

**Comment by gcmms** [comment]
> Não, o YouTube não tem API para isso e, por não existir Webview no tvOS não é possível usar esse exemplo e também não acho legal direcionar o usuário para o App YouTube, até porque, basta ele assinar o canal MM e ir direto, sem a necessidade de ser redirecionado. Como UX não acho legal, como usuário não vejo benefícios e como técnico, não vejo solução, infelizmente.

Ok, concordo com você

**Comment by cassio-rossi** [comment]
Vamos fechar esse issue? @rfischmann @eduardomarqu-es

**Comment by rfischmann** [comment]
Pena, mas ok.
