### ISSUE TITLE
Bug no Layout

### ISSUE THREAD

**Issue by Themakew** [MacMagazine/app-iOS#172]
Para reproduzir o bug é necessário os seguintes passos:
1 - Pesquisar algum post na aba de posts;
2 - Cancelar a pesquisa;
3 - Realizar uma nova pesquisa.

Depois desses passos, os buttons de favoritos e busca ficam desalinhados do layout original:

![3404120C-1A2B-4938-AF51-9618C789DA42](https://user-images.githubusercontent.com/3030029/59452638-8a11e800-8de4-11e9-887b-5df27b987223.png)

**Comment by rfischmann** [comment]
Corrigido na 4.1, já liberada na App Store.
