### ISSUE TITLE
Sugestão: Download de posts

### ISSUE THREAD

**Issue by ggirotto** [MacMagazine/app-iOS#174]
Boa tarde/noite pessoal. Acompanho a MacMagazine de maneira diária faz pouco mais de um ano, e gostaria de estar contribuindo para o projeto do app. Venho aqui trazer a sugestão da funcionalidade para que o usuário consiga baixar um post para ver offline mais tarde. Gostaria de saber o que vocês acham da sugestão. Estou estudando o código e acho essa uma funcionalidade bem interessante para o app.

**Comment by kazziosoftware** [comment]
Essa funcionalidade existe na forma de cache nativa do App.
Todos os posts são salvos em uma base de dados e o conteúdo propriamente dito é salvo em cache uma vez que for aberto.
É bastante complicado salvar a página renderizadas propriamente dito, sem por causa das imagens e do conteúdo naturalmente dinâmico, sem contar o espaço que ocuparia.

**Comment by rfischmann** [comment]
Talvez algo que o app possa fazer automaticamente é carregar os posts em plano de fundo e armazenar nesse cache local no momento em que forem marcados como favoritos. Enquanto estiverem nos favoritos, estão também em cache.

**Comment by kazziosoftware** [comment]
Isso acabaria com o pacote de dados do usuário além de não garantir que o conteúdo irá para cache, já que tudo é gerenciado automaticamente pelo WKWebView. Não acho uma boa idéia (essa maneira).
Acho que seria interessante pensar em algum sistema de votação para escolher idéias para, de fato, ir para desenvolvimento.

**Comment by ggirotto** [comment]
Verdade :/
Utilizando o cache da WKWebView de fato não faz tanto sentido essa funcionalidade. Acredito que qualquer coisa nesse viés seria apenas por fazer e não algo que irá agregar de fato.
Obrigado pelo feedback pessoal.

Aproveitando o tópico, vocês pensam em migrar para uma estrutura sem WebView criando o layout pelo app mesmo?

**Comment by rfischmann** [comment]
A priori não, @ggirotto. Tornaria o projeto todo bem mais engessado e dependente, hoje temos a flexibilidade de mexer em certas coisas na versão mobile do site e isso se reflete automaticamente no app.

**Comment by ggirotto** [comment]
Perfeito. Muito obrigado pelo retorno pessoal. Não tinha analisado estes pontos quando fiz essa sugestão. De fato, hoje uma funcionalidade de baixar os posts não faz sentido dados os problemas e dependências que isso gera. Vou pensar em alguma outra coisa interessante para sugerir. Talvez quem sabe uma versão para Apple TV como já sugeriram em outro issue.

**Comment by kazziosoftware** [comment]
@rfischmann podemos fechar esse issue? A idéia do AppleTV é boa.
