### ISSUE TITLE
Posts duplicados na lista

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#180]
Parece que esse bug ainda não foi solucionado 100%: https://d.pr/i/2GuIfz

Também já vi acontecer aqui 1-2 vezes.

**Comment by rfischmann** [comment]
Na verdade para "resolver" é até mais simples: só limpar o cache do app.

Mas o porquê que acontece de vez em quando, eu não sei.

**Comment by Lailan** [comment]
Aconteceu comigo hoje, inclusive mandei um video no twitter onde o problema acontecia.

**Comment by rfischmann** [comment]
@Lailan Não é um bug no app, eu é que disparei o push de novo sem querer. Foi só essa vez, né?

**Comment by Lailan** [comment]
@rfischmann sim, apenas dessa vez. Não me atentei que havia recebido o push duas vezes.

**Comment by rfischmann** [comment]
Sobre o post duplicado na tela inicial, é que editei o título logo depois de publicar. Limpa o cache do app que resolverá.

**Comment by kazziosoftware** [comment]
Em uma ocasião percebi que o problema é que a URL no WP muda, o que gera um post duplicado. Acho  muito difícil corrigir isso no App e sugero orientar a limpar o cache como solução

**Comment by kazziosoftware** [comment]
Podemos fechar esse issue?

**Comment by rfischmann** [comment]
@kazziosoftware Para evitar que isso aconteça quando mudamos título e/ou URL, acho que o app poderia verificar a duplicidade pelo ID do post. Há uma linha no feed que serviria para isso, exemplo:

`<post-id xmlns="com-wordpress:feed-additions:1">677901</post-id>`

Acha que rola, Cássio?

**Comment by kazziosoftware** [comment]
Esse campo é novo né? Sim, funcionará.

**Comment by rfischmann** [comment]
Acho que não é novo, não. A gente que nunca foi atrás disso. 😄
