### ISSUE TITLE
Sugestão de feature (handoff)

### ISSUE THREAD

**Issue by Themakew** [MacMagazine/app-iOS#182]
Acredito que o aplicativo poderia dar suporte ao handoff, podendo utilizar o mac para continuar a navegação de posts, podcasts e videos.

**Comment by rfischmann** [comment]
Seria legal, mesmo. Com um post aberto no app, apareceria no canto do Dock um ícone do navegador padrão (não sei se funciona com qualquer um ou só com o Safari) que quando clicado abriria o mesmo post.

**Comment by kazziosoftware** [comment]
Acho que isso poderia ficar para o App nativo macOS depois do Catalina. Ai fica moleza, moleza.

**Comment by rfischmann** [comment]
Mesmo com o Catalyst, não vejo muito motivo para um app nosso no macOS viu…

**Comment by Themakew** [comment]
Acredito que o handoof resolveria também, no macos já tem o site web que faz mais sentido. De novas plataformas eu acredito que só a apple tv poderia entrar.
