### ISSUE TITLE
Bug na tela de post

### ISSUE THREAD

**Issue by Themakew** [MacMagazine/app-iOS#186]
A indicação do dia fica bugada quando coloca para atualizar os posts:

![1C729C39-7B0E-4CDB-9816-86D5A4C80254](https://user-images.githubusercontent.com/3030029/61456052-86b9d100-a93b-11e9-85a3-1a40016c088a.jpeg)

**Comment by rfischmann** [comment]
Corrigido na 4.1, já liberada na App Store.
