### ISSUE TITLE
Posts - Puxe para atualizar não volta ao ponto de origem

### ISSUE THREAD

**Issue by leschlogl** [MacMagazine/app-iOS#188]
Na tela de posts, quando realizamos o puxe para atualizar, o ponto de origem da lista não volta ao topo, ficando o espaço de onde ficava o carregando.

**Device**: iPhone 8
**iOS**: 12.3.1
**Branch**: release/4.0

![posts_pulltorefresh](https://user-images.githubusercontent.com/6379664/63880242-bf6db100-c9a3-11e9-9d57-3d81f6b6b5a1.gif)

**Comment by rfischmann** [comment]
Devido a esse bug chato, a gente decidiu trocar a animação de atualização para o local onde fica o logo. Acho que o @kazziosoftware já implementou isso na última beta do app.

**Comment by kazziosoftware** [comment]
Podemos fechar esse issue?

**Comment by rfischmann** [comment]
Sim.
