### ISSUE TITLE
Bug ao abrir post via push notifications 

### ISSUE THREAD

**Issue by Themakew** [MacMagazine/app-iOS#190]
Ao abrir um post via push notification a tela perde a referência da navigation e não é possível voltar para a home screen:

![Image](https://i.imgur.com/vxgFVvQ.jpg)

**Comment by rfischmann** [comment]
Mais um relato: https://twitter.com/alexberaldo/status/1182081346052730880

**Comment by kazziosoftware** [comment]
não consigo reproduzir usando iPhone 11 e iOS 13.1.2. Talvez precise de mais detalhes.

**Comment by Themakew** [comment]
Comigo só foi clicar mesmo no post notification, talvez tenha a ver com o app estar fechado (sem estar em background), não sei ao certo, tem que testar nos mais diferentes cenários. 

Relacionado a isso também, ontem recebi post notification duplicado.

**Comment by kazziosoftware** [comment]
Meu App fica sempre fechado e está Ok.
Push duplicado é um problema conhecido sem solução.

**Comment by rfischmann** [comment]
A parte dos _pushes_ duplicados eu estou trabalhando com o suporte do OneSignal para resolver. Não é bug no app.

**Comment by rfischmann** [comment]
Acho que isto aqui já foi resolvido, né?

**Comment by kazziosoftware** [comment]
Acho q sim.
