### ISSUE TITLE
Identificar/filtrar posts já lidos

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#192]
Sugestão recebida por email:

> **Yudi Osugui**
> 
> Na verdade não é um problema, mas gostaria de sugerir quando um post for visto, poderia mudar de cor o texto ou talvez ter um filtro de posts não vistos. 
> 
> Obrigado por todos esses anos de MacMagazine.

**Comment by kazziosoftware** [comment]
Parece interessante mas não acho prático nem tecnicamente nem em termos de UX.
Tecnicamente, seria necessário alterar a base, a interface para mostrar um ícone, adicionar uma opção no filtro (tudo isso é fácil). Mas iria quebrar o Limpar Cache - e ai vem o problema de UX, todos os posts, inicialmente seriam considerados não lidos e, toda vez q fizer um Limpar Cache, os posts seriam marcados como não lidos novamente.

**Comment by rfischmann** [comment]
Eu ainda não sei se é uma sugestão realmente boa e que deve ser implementada, mas só respondendo algumas das coisas que levantou:

- Não precisaria de um ícone, basta "esmaecer" (adicionar um pouco de transparência) à linha dos posts já lidos.
- Sim, inicialmente todos os posts seriam considerados não-lidos. Mas acho que a opção de limpar cache não deveria influenciar no que já foi lido ou não, seria uma base separada.

**Comment by rfischmann** [comment]
Está na versão 4.2, saindo na próxima segunda-feira.
