### ISSUE TITLE
Mais fontes e/ou opção dinâmica

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#200]
Comentário de leitor lá no site:

> **Marcelo Fullclick**
> 
> Rafael Fischmann , primeiro gostaria muito de parabenizar vcs pelo excelente trabalho e ampla atenção ao aplicativo de vcs!
> 
> Aqui, gostaria muito de dar uma pequena sugestão. Nas configurações, em tamanhos de fontes, vcs poderiam colocar mais um tamanho, ou dois, de fontes. Pq mesmo no tamanho máximo, no iPhone, ainda fica pequeno e de difícil leitura. Se pusessem mais tamanhos, ficaria ainda melhor. Eu, assim como muitos, usam óculos e, dependendo do grau, fica difícil a leitura.
> 
> Seria legal tb colocar fontes adaptativas, que se adaptam ao tamanho de fonte definida no sistema!
> 
> No mais, contribuem com o ótimo trabalho e parabéns novamente!

Tenho minhas dúvidas sobre a necessidade de mais opções de tamanhos, mas a ideia de seguir a configuração de fonte dinâmica do sistema é boa, hein?

**Comment by Themakew** [comment]
@rfischmann quanto a parte nativa é relativamente simples de fazer, o problema seria nas webviews para acompanhar o resto nativo. Acredito que tenha que resolver essa parte para implementar a funcionalidade por completo.

**Comment by rfischmann** [comment]
@Themakew Creio que meu trabalho seria só criar mais folhas de estilo para cada "tracinho" do ajuste de tamanho de texto, né? Hoje temos 3 só, aumentaria para 7. É isso?

**Comment by cassio-rossi** [comment]
Seguir o sistema é um pouco mais complicado do que só incluir novos css para as WebView. Hoje o layout, que foi feito seguindo a versão anterior, tem seu tamanho fixo, logo, aumentar a fonte significa truncar ainda mais o conteúdo.
Para seguir o sistema - que é correto, diga-se de passagem - seria necessário rever todo o layout.
Como ficam os títulos? E os sub-título? A limitação seria por quantidade de linhas? Mostraria tudo? Enfim, muitas questões de design a serem discutidas antes de se tomar uma decisão.
Tecnicamente, sim, é simples de se fazer.

Fonte mínima:
![IMG_2200](https://user-images.githubusercontent.com/843304/83362876-b1aee700-a38c-11ea-894a-2e906dda8ac8.jpeg)

Fonte boa (para mim):
![IMG_2201](https://user-images.githubusercontent.com/843304/83362884-c12e3000-a38c-11ea-9b5f-df330e2856e3.jpeg)

Fonte máxima:
![IMG_2199](https://user-images.githubusercontent.com/843304/83362890-c7241100-a38c-11ea-9c4c-73cd238f0b27.jpeg)

**Comment by rfischmann** [comment]
@cassio-rossi Boas questões. Não seria possível implementarmos isso numa beta e, vendo a coisa funcionando, irmos fazendo esses ajustes todos? Creio que, por exemplo, no ajuste maior a gente deva esconder as primeiras linhas do post, deixando apenas o título. Já no menor, podemos aumentar de 3 para 4 linhas o preview. Só dois exemplos.

**Comment by Themakew** [comment]
@cassio-rossi Para evitar essas fontes enormes ou muito pequenas, tem como configurar um máximo e mínimo. Acredito ser melhor do que deixar totalmente livre como nas imagens.

**Comment by rfischmann** [comment]
Está na versão 4.2, saindo na próxima segunda-feira.
