### ISSUE TITLE
MM Live no app

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#201]
Vi [esse tweet](https://twitter.com/GarotoMdolla/status/1275061576156889094) e a ideia é realmente boa.

Poderíamos ter um "switch" remoto para ativarmos uma aba do MM Live no dia de keynotes como hoje, que carregaria a página https://macmagazine.uol.com.br/live/ no app. Coisa bem simples, mas necessária de fato.

Não sei como nunca pensamos nisso antes.

**Comment by Themakew** [comment]
Como seria esse switch remoto?

**Comment by rfischmann** [comment]
Não tenho certeza ainda, mas pode ser até um arquivo XML ou JSON que o app lê no nosso servidor.

**Comment by rfischmann** [comment]
Estará na 4.4.
