### ISSUE TITLE
Widget para o iOS 14

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#202]
Acho que cairá muito bem oferecermos, futuramente, um widget do app no iOS 14 mostrando talvez um preview do último post publicado. 😉

**Comment by ailtonvivaz** [comment]
Opa, pode contar comigo com isso. Vou fazer algo inicial. Qual seria a ideia? (já que ainda estamos em beta)
Podemos lançar já em testflight?

**Comment by rfischmann** [comment]
Valeu, @ailtonvivaz! Eu só pensei mesmo em mostrar um preview do último post publicado, com imagem e título. Talvez nem role em todos os formatos de widget, penso que no menor de todos não fique muito legal…

E sim, podemos lançar no TestFlight. Talvez o ideal, nesse caso, é criarmos um _branch_ focado numa futura atualização do app para o iOS 14.

**Comment by ailtonvivaz** [comment]
Não estou conseguindo rodar o projeto no Xcode 12, tá dando problemas nos binários das libs. Acredito que o Carthage ainda não está com suporte para o Swift 5.3

**Comment by ailtonvivaz** [comment]
Pensei nos widgets assim. O que acham?
Seria legal, também, o usuário poder configurar por tópico.
| Small             |  Medium 1 
:-------------------------:|:-------------------------:
![Small](https://user-images.githubusercontent.com/12598328/85910664-86d27a00-b7f6-11ea-82ad-49742d17d714.PNG) |![Medium1](https://user-images.githubusercontent.com/12598328/85910661-85a14d00-b7f6-11ea-91e1-706be48e8687.PNG)

| Large | Medium 2
:-------------------------:|:-------------------------:
![Large](https://user-images.githubusercontent.com/12598328/85910660-84702000-b7f6-11ea-92a7-a21ac4fe1d82.PNG) |![Medium2](https://user-images.githubusercontent.com/12598328/85910719-f0528880-b7f6-11ea-81bf-a6fb12a83db5.PNG)

**Comment by rfischmann** [comment]
Ficou muito legal!! 😊

**Comment by cassio-rossi** [comment]
Vou criar uma branch para iOS14 com as bibliotecas atualizadas.

**Comment by cassio-rossi** [comment]
@ailtonvivaz me adiciona no seu Telegram para conversarmos mais interativamente - nem sempre olho aqui o Git. Meu user é @cassiorossi. Tenho planos para SwiftUI e sua ajuda por ser útil.

**Comment by ailtonvivaz** [comment]
Opa @cassio-rossi, enviei solicitação lá.

**Comment by cassio-rossi** [comment]
Não recebi nada ainda. Qual é seu username no Telegram?

**Comment by rfischmann** [comment]
Será que conseguimos implementar isso na 4.3?

**Comment by ailtonvivaz** [comment]
Acredito que sim. Está em andamento.

**Comment by rfischmann** [comment]
Lançaremos esta semana, na 4.3!
