### ISSUE TITLE
Mais espaço para os títulos

### ISSUE THREAD

**Issue by wiliamjk** [MacMagazine/app-iOS#204]
Estou usando ativamente o app agora, mas uma coisa me incomoda muito. O limite de caracteres dos títulos implica que uma quantidade considerável de chamadas para posts não podem ser lidas por completo. Teria como aumentar esse limite?

**Comment by rfischmann** [comment]
É um bom ponto, @wiliamjk. Abri aqui e olhei os últimos 20 posts, 8 estão com o título cortado — quase metade.

Acho que podemos aumentar para 3 linhas, @cassio-rossi?

**Comment by rfischmann** [comment]
Está na versão 4.2, saindo na próxima segunda-feira.
