### ISSUE TITLE
Bug na webview

### ISSUE THREAD

**Issue by Themakew** [MacMagazine/app-iOS#209]
Ao clicar no botão de abrir os comentários, em vez disso, outra webview é aberta com a mesma notícia. Pelo padrão novo do app deveria abrir a tela modal com a webview dos comentários.

![IMG_6446](https://user-images.githubusercontent.com/3030029/97233482-cb2e5080-17bd-11eb-8480-ed927a63629d.jpg)

**Comment by rfischmann** [comment]
@cassio-rossi Acho que não rola alterar esse comportamento com o link como está, rola? Se for o caso, eu simplesmente escondo isso aí no app.

**Comment by cassio-rossi** [comment]
@rfischmann voce pode colocar o mesmo link do botão Ver Comentários.

**Comment by rfischmann** [comment]
Mas isso é um link do tema, eu não consigo personalizar isso assim. Aquele botão eu adicionei manualmente no final dos posts, aí personalizei o link como você me orientou.

**Comment by cassio-rossi** [comment]
> Mas isso é um link do tema, eu não consigo personalizar isso assim. Aquele botão eu adicionei manualmente no final dos posts, aí personalizei o link como você me orientou.

Ok. Então eu mudo do lado do App.

**Comment by rfischmann** [comment]
Você consegue?

**Comment by cassio-rossi** [comment]
> Você consegue?

Sure. Basta interceptar a URL e tomar uma ação. Pode dar um pouquinho de trabalho mas dá para fazer. Mas se você achar melhor esconder isso...

**Comment by Themakew** [comment]
Eu mesmo gosto da funcionalidade , inclusive teria na home dos posts também para já abrir direto os comentários kkk

**Comment by rfischmann** [comment]
Estará na 4.2.1.
