### ISSUE TITLE
Bug de Loading Infinito

### ISSUE THREAD

**Issue by Themakew** [MacMagazine/app-iOS#210]
Ao abri o app, estou tendo um loading infinito dos posts e não carrega nenhum post novo:

![animated](https://user-images.githubusercontent.com/3030029/97906748-f5828f80-1d22-11eb-9aab-4a1c8ec1cc21.gif)

**Comment by rfischmann** [comment]
Foi só o nosso servidor disparado, estamos resolvendo um problema relacionado a isso. Não é nada no app.

Fechando esta issue.
