### ISSUE TITLE
Bug no Botão de Comentários

### ISSUE THREAD

**Issue by Themakew** [MacMagazine/app-iOS#211]
Estou tendo que dar um duplo clique no botão de abrir os comentários (Ver comentários do post) para de fato abrir (a ação ser executada):

![IMG_351F092A62D3-1](https://user-images.githubusercontent.com/3030029/97906914-35e20d80-1d23-11eb-88aa-b8102f47ea4e.jpeg)

**Comment by rfischmann** [comment]
Também não é um problema no app, e sim no tema mobile do nosso site. Estamos trabalhando para corrigir isso, valeu pelo report.
