### ISSUE TITLE
Bug: Lag na Abertura do Post

### ISSUE THREAD

**Issue by Themakew** [MacMagazine/app-iOS#212]
Estou vendo que tem um lag considerável, em alguns posts, para abrir a webview. Talvez parte do processamento de abertura da webview passou a ser feito na tela de listagem, caso for isso, gerou um problema de usabilidade no app pelo fato de ter um travamento no app até o post abrir (dado que não há nenhum feedback visual para o usuário que algo está sendo processado):

![animated 2](https://user-images.githubusercontent.com/3030029/97907329-e3552100-1d23-11eb-9a67-2d9d72e1dde6.gif)

**Comment by cassio-rossi** [comment]
Não há nenhum pré-processamento antes de abrir o post. Deve ser bug do iOS 14 mesmo.

**Comment by rfischmann** [comment]
Fecho esta issue, então?
