### ISSUE TITLE
Bug na header dos dias

### ISSUE THREAD

**Issue by Themakew** [MacMagazine/app-iOS#213]
Esse bug ocorre recorrentemente, no print tem dois bugs: duas headers com a mesma data (hoje) e um sobrepondo os posts.

![image](https://user-images.githubusercontent.com/3030029/100864715-274b5b00-3475-11eb-8d85-eab64851ff20.png)

**Comment by rfischmann** [comment]
Alguma forma fácil/conhecida de reproduzir esse bug? Eu nunca vi aqui.

**Comment by rfischmann** [comment]
Como não temos mais relatos disso, vou fechar a issue por ora.
