### ISSUE TITLE
Notificação única

### ISSUE THREAD

**Issue by cassio-rossi** [MacMagazine/app-iOS#215]
Falta função ‘única notificação’

by Andrade_F – Feb 26, 2021
Gostaria que tivesse a função onde é enviado apenas uma notificação por dia, no horário que eu quiser, com todas as postagens feitas no dia, ao invés de receber 1 notificação para cada postagem. (Existe a função no YouTube, se pudessem copiar seria ótimo)

**Comment by rfischmann** [comment]
Complicado com o sistema atual do OneSignal, né? A menos que o app tivesse uma base que fosse "guardando" essas notificações e depois disparasse em determinado momento.

Mas como seria isso? Numa determinada hora, o cara receberia trocentos pushes de uma vez só? Nunca vi um app fazer isso…

**Comment by maclacerda** [comment]
Eu não conheço o `One Signal` a fundo, entretanto, se o sistema de Push fosse usando um `Firebase` da vida, poderíamos criar um "channel" que seria tipo "diario" e poderíamos adicionar a na tela de Settings do app para que o usuário selecione essa opção, caso ele selecionasse, poderíamos dar a opção do mesmo escolher em qual parte do dia (manhã / tarde / noite) ele receberia a notificação, e poderíamos colocar um "cron job" ou usar os jobs do próprio firebase para realizar o disparo, sendo que o horário escolhido poderíamos definir em qual hora a notificação seria enviada, por exemplo, manhã as 10hr, tarde as 15hr e noite as 19hr.

**Comment by rfischmann** [comment]
@maclacerda Essa parte técnica de como a coisa funcionaria não é muito comigo, estou pensando mais na prática. Não seria só uma única notificação, né?

**Comment by maclacerda** [comment]
@rfischmann em suma, temos que entender se o OneSignal permite trabalhar com o conceito de "tópicos" que o Firebase tem. Se ele tiver, conseguimos fazer com que os usuários que assim o desejarem recebam apenas 1 push por dia em um horário que podemos definir ou deixar com que o usuário escolha.

**Comment by rfischmann** [comment]
Mas é isso que eu tou questionando. O que teria nesse push único? Uma coisa é o cara receber por exemplo um email no fim do dia com todas as matérias-destaque publicadas no site, outra é um simples push.

**Comment by maclacerda** [comment]
A sim, desculpe, não entendi a pergunta. Então, acho que poderíamos colocar algo tipo "Veja o que aconteceu de mais importante no mundo da Maçã" (ou qualquer outro tipo de texto). E se o usuário clicar nesse push, ele seria levado para dentro do app na tela principal do mesmo. Funcionaria mais como um "lembrete" que ele ainda não viu as postagens do dia.

Ou até mesmo, poderíamos evoluir isso em uma segunda versão para levar o usuário para uma lista apartada com os posts do dia. Mas isso é algo que podemos maturar.

Consegui esclarecer sua dúvida / responder sua pergunta Rafa?!

Abraços

**Comment by rfischmann** [comment]
Então, sendo assim eu acho inútil e não precisaríamos de sistema especial nenhum. Bastaria programar um cron job de um push genérico desse para ser disparado 1-2x por dia, e basicamente serviria de "lembrete" pro cara abrir o nosso app e ver o que rolou no dia — e acho que encheria o saco da galera rapidinho. 😜

**Comment by maclacerda** [comment]
Pois então a issue seria justamente relacionada a isso, pelo que eu entendi, alguns usuários não querem ser notificados a cada novo post, mas sim, uma única vez no dia. A ideia que sugeri desse mecanismo de disparo seria justamente para os usuários que não querem ser notificados a cada post, mas também não querem desativar todas as notificações 😊

**Comment by rfischmann** [comment]
Pois é, mas a única coisa que eu realmente acho que faria um pouco de sentido nesse cenário seria, de uma vez só, o cara receber várias notificações numa determinada hora do dia da sua escolha. Só que nunca vi app nenhum se comportar assim… tou achando que isso aqui é meio inviável.

**Comment by maclacerda** [comment]
Bom, daria até para ser implementado dessa forma, podemos mandar o que chamamos de "push fantasma", o app ao recebe-lo iria ler todos os posts do dia e criar notificações (que chamamos de `local notifications`) e mandaria uma para cada post do dia. Mas acho que isso seria meio `over engineering`, acredito que talvez o número de pessoas que iriam "aderir" a esse modelo seria bem baixo, sem contar, que eu particularmente acho meio bizarro receber todas as notificações de uma única vez.

**Comment by rfischmann** [comment]
Concordo, @maclacerda. Eu realmente tou achando que esta _issue_ não tem muito futuro…

**Comment by cassio-rossi** [comment]
Vamos fechá-lo então?

**Comment by rfischmann** [comment]
@eduardomarqu-es Concorda em fecharmos isto?

**Comment by eduardomarqu-es** [comment]
E o "Resumo de notificações" do iOS 15 meio que ajuda nesse sentido, não?

**Comment by rfischmann** [comment]
> E o "Resumo de notificações" do iOS 15 meio que ajuda nesse sentido, não?

Vero.
