### ISSUE TITLE
Piscadela ao abrir post enquanto cookie não é processado

### ISSUE THREAD

**Issue by cassio-rossi** [MacMagazine/app-iOS#216]
Bug
by Anderson C. Lopes – Mar 2, 2021

O aplicativo tem um bug horrível, todas as vezes em que vou ler um artigo, ao abri-lo tudo fica com o fundo branco e só depois de uns 10 Segundos que fica escuro, isso sempre acontece e desde sempre!

**Comment by rfischmann** [comment]
É a velha questão de carregar o CSS escuro. Não sei como resolver isso, mas aqui definitivamente não leva 10 segundos; às vezes nem sequer "pisca", mas algumas vezes eu vejo por uns 2-5 segundos sim.

**Comment by rfischmann** [comment]
Estará na 4.4.1.
