### ISSUE TITLE
Mostrar posts mais lidos no Widget

### ISSUE THREAD

**Issue by wiliamjk** [MacMagazine/app-iOS#219]
Eu estou usando o widget do app do MacMagazine na minha home screen e eu notei que ele mostra as últimas notícias. 

O problema é que tem momentos em que a última notícia não é a mais relevante. 

Por exemplo:
- Quando é um dia com muitos posts (como em dias de keynote), pode ser que um post importante seja rapidamente escondido por outro post publicado logo na sequência.
- Quando passa muito tempo sem novos posts (como nos finais de semana), pode ser que um post não muito relevante fique visível muito tempo, só porque ele foi o último a ser publicado.

Pensando nisso, acho que dava para, ao invés de mostrar o último post, mostrar o post mais lido no site nas últimas X horas. Ou talvez dar essa opção para o usuário. O que vocês acham?

**Comment by rfischmann** [comment]
Obrigado pela sugestão, @wiliamjk!

Estou só pensando aqui se isso não poderia ficar confuso para o usuário. Logo de cara, creio que por padrão o widget deveria continuar mostrando os últimos posts, e aí se a pessoa quiser alterar para os mais lidos nas últimas 24h, teria essa opção e saberia o que está fazendo.

Até temos um plugin que contabiliza views em posts para uma área de tendências na parte inferior da nossa home, mas o app provavelmente teria que acessar esses dados diretamente no nosso banco de dados. Não sei se haveria uma forma melhor de isso funcionar, e também nem sei de quanto em quanto tempo ele faria isso.

Quem sabe, fosse necessário um script rodando periodicamente em nosso servidor que gerasse então um XML o qual o app consultaria…

**Comment by cassio-rossi** [comment]
@rfischmann acho q esse issue pode ser encerrado, concorda? v4.5

**Comment by rfischmann** [comment]
Acho que sim.
