### ISSUE TITLE
Banner de propaganda bloqueia o botão de `Ver Comentários do Post` nas visualizações do iPad

### ISSUE THREAD

**Issue by brunomyrrha** [MacMagazine/app-iOS#220]
**BUG:** A propaganda bloqueia o botão de acesso aos comentários dos posts como demonstrado nas screenshots abaixo. Se isso já foi discutido ou não for interessante de ser resolvido por quaisquer razões, podem fechar a issue.
**(iPad Air 4th Gen)**

![IMG_7BD8C671BC9A-1](https://user-images.githubusercontent.com/9771570/163995892-3ee0da78-5022-44fa-952d-345f1e07d4d8.jpeg)
![IMG_285D4A972CF6-1](https://user-images.githubusercontent.com/9771570/163995894-a6d1f44e-8e3b-442e-8162-533b3c126d49.jpeg)
![IMG_C64DE787F920-1](https://user-images.githubusercontent.com/9771570/163995896-d314af53-fb0f-4798-b7d5-140b0a164482.jpeg)

**Comment by rfischmann** [comment]
Obrigado pelo relato, @brunomyrrha. Daria para resolver isso via CSS, mas estamos reconsiderando o uso desse banner fixo no rodapé com o pessoal do UOL.

**Comment by brunomyrrha** [comment]
Obrigado pelo retorno. Eu imaginei que fosse algo na página em si. Vou procurar outra coisinha pra tentar ajudar no projeto.

**Comment by cassio-rossi** [comment]
Acho que esse issue já está resolvido, certo @rfischmann ? Eu não vejo mais bloqueio no rodapé dos posts, nem no iPad nem no iPhone.

**Comment by rfischmann** [comment]
Sim, eu resolvi aqui no CSS.
