### ISSUE TITLE
Clicar em Posts não retorna para home se abriu app pela notificação

### ISSUE THREAD

**Issue by renatocpn** [MacMagazine/app-iOS#221]
Quando abrimos o App na aba Posts por padrão e clicamos em uma notícia, podemos clicar em "Posts" na aba inferior e voltamos para a home, a lista de notícias.

Quando abrimos uma notícia direto a partir das notificações, a única forma de voltar para a home é pelo botão voltar no topo. Clicar na aba "Posts" não navega para a home. Podemos mudar de aba sem problema, aí quando clicamos em "Posts" voltamos para a notícia que estava abera (Ok), e mesmo assim o segundo clique (com "Posts" ativo) não direciona para a home.

**Comment by rfischmann** [comment]
Você está certíssimo na sua observação, @renatocpn! Realmente, faz sentido.

O @cassio-rossi já começou a trabalhar na versão 5.0 do nosso app, com um código totalmente novo, e isso aí provavelmente será corrigido nela. 😊
