### ISSUE TITLE
Margens incorretas nos widgets

### ISSUE THREAD

**Issue by 0xsoria** [MacMagazine/app-iOS#224]
Margens excessivas nos widgets da tela inicial.
Isso foi introduzido no iOS 17 e é um problema simples de resolver.

 ![image](https://github.com/MacMagazine/app-iOS/assets/24867592/76e128dd-f77c-42ab-8aef-8feccf6d2342)

**Comment by 0xsoria** [comment]
Pull request aberto - fiz o PR para a branch v4 pois não encontrei nada dos widgets na v5 🤔 Posso mudar caso tenha feito errado.

https://github.com/MacMagazine/app-iOS/pull/225

**Comment by cassio-rossi** [comment]
v5 ainda está em desenvolvimento.
Obrigado pela colaboração.
