### ISSUE TITLE
Improvement: Integrar ao Buddybuild

### ISSUE THREAD

**Issue by rgalba** [MacMagazine/app-iOS#47]
Gostaria de sugerir uma melhoria para o processo de deploy, distribuição e feedback do app: configurar e utilizar o [https://buddybuild.com](url).

Prós:
- Builds automáticos (com testes e logs) a cada novo commit
- Integração com Cocoapod, Carthage( 🎱 ), Github, Bitbucket.
- Build em multiplas versões beta/GM do Xcode (útil para testar versões sem instalação local)
- SDK de feedback integrado: Para enviar feedback, o usuário basta tirar uma screenshot, marcar a área do erro e escrever. O time recebe um email com os detalhes. Isso. Simples assim.
- Video de evidência de bug de até 15s antes dá app quebrar
- Adição de usuário beta via e-mail. O usuário de teste instala as novas releases via email.
- Controle de release por "times". Um time de QA pode receber releases diferentes do time "Pré-release"
- Integração com Itunes Connect.
- Free/Grátis/0800

Cons: (existe?)
- Se encontrar algum, me avise :)

Tenho usado em 4 apps, e o processo de feedback dos usuários de teste é muito melhor. Incluir o cliente no processo de dev desde o começo faz muita diferença. Além disso, o próprio BuddyBuild faz o commit configurando o SDK. 
Eu não tenho como enviar uma PR com isso, pois é preciso que o developer da conta da app store, crie e conecte suas credenciais no BuddyBuild.

Com certeza, isso vai melhorar o processo de feedback e melhoria do app. 
Qualquer dúvida, estou a disposição.

ps: eu não trabalho no BuddyBuild. Apenas acho que a maneira como eles estão fazendo esse serviço: IT IS AWESOME!

**Comment by Viniciuscarvalho** [comment]
@rgalba vai ser free só até um determinado tempo viu esse buddybuild 👍 

Lá embaixo do site ele diz, `Pricing coming soon!`

Então essa maravilha ae daqui um tempo vai acabar heheh

**Comment by rgalba** [comment]
@Viniciuscarvalho  Na pagina eles dizem que sempre terão um plano grátis:

>
But one thing's for sure: we'll always offer a free tier to meet your app building needs.
>

E acredito que para projetos open source como esse, aí que vai ser mais fácil.

**Comment by Viniciuscarvalho** [comment]
@rgalba é o que essas ferramentas não oferecem todo seu bundle em versões free, por isso não não sei se valeria a pena implementar no projeto todo.
Mas é uma ferramenta incrível mesmo 👍

**Comment by cesarbars** [comment]
A ferramenta parece ótima, mas não sei se cabe para um side-project open-source como esse do MM. Não sei se temos volume suficiente para justificar uma adição como essas.

**Comment by rgalba** [comment]
@cesarbars tenho algumas perguntas sobre isso:

- Você executam builds em pré-releases do Xcode? Tem máquinas alocadas pra isso?
- Tem alguma ferramenta para controle do relatório de erros?
- Tem alguma ferramenta para evidencia de bug com video?

Realmente foi só uma sugestão, mas sei que o BB pode resolver todos esses problemas, ressaltando a enorme vantagem do primeiro ponto.

**Comment by Viniciuscarvalho** [comment]
@rgalba será que mesmo pago agora o BB valeria a pena aplicado ao projeto?

**Comment by Themakew** [comment]
@rfischmann @kazziosoftware @fsaragoca Há algum interesse por parte da equipe de implementar essa issue? Caso contrário poderia fecha-la.
