### ISSUE TITLE
Sistema de busca de posts

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#49]
A ideia seria um campinho de busca no topo do app, ao puxar a tela para cima, que sirva para usuários encontrarem posts em todo o site.

O [Luigi Freitas](https://luigifreitas.me/), que desenvolveu o nosso _bot_ para o Telegram, me parece que está desenvolvendo uma espécie de API para o próprio _bot_ ter o seu sistema de buscas. Se não me engano, ele está fazendo isso baseado na [WordPress REST API](https://wordpress.org/plugins/rest-api/), cujo plugin já está instalado e ativo no MacMagazine. Com isso concluído, segundo ele, daria para integrar o trabalho ao app.

**Comment by rgalba** [comment]
@rfischmann teria a API de busca para testes? Pode informar aqui na issue?

**Comment by luigifreitas** [comment]
Assim que ela estiver pronta solto ela OpenSource aqui com as rotas REST. Ela vai ser baseada em ElasticSearch, ou seja, vai ser mais rápida que o plugin :D

**Comment by rphlfc** [comment]
@rgalba, você pode acessar alguns métodos (os GET's, nada de POST/PUT/DELETE a não ser que você tenha login/password) da WordPress REST API independente da busca que o @luigifreitas está construindo. Os métodos estão descritos na documentação (http://v2.wp-api.org/reference/) e o próprio WordPress disponibiliza uma biblioteca em Objective-C (https://github.com/wordpress-mobile/WordPress-API-iOS) para fazer requisições. A vantagem de esperar o @luigifreitas é que o WordPress não disponibiliza nenhum método para realizar buscas nos posts e é exatamente isso que ele está fazendo (acredito eu).

**Comment by cesarbars** [comment]
@rphlfc  Já exploramos a API do WordPress no passado sem muito sucesso, mas não demos lá muita atenção à época.
@luigifreitas existe um roadmap da API?

**Comment by luigifreitas** [comment]
@cesarbars Yep, fiz um [repositório do search](https://github.com/luigifreitas/macmagazine-elasticsearch-api) hoje cedo. Ainda não tem nenhum código, o qual deve ser adicionado em breve, mas já conta com um rascunho da rota de pesquisa. 😃

**Comment by luigifreitas** [comment]
A API funcional já esta disponível. Toda a documentação esta [aqui](https://github.com/luigifreitas/macmagazine-elasticsearch-api). 🎉

**Comment by kazziosoftware** [comment]
@luigifreitas testei a API de Search e me parece q não está 100%. Procurei por WWDC e não apareceram os mesmos posts que tem no site. Por exemplo, não apareceu nada de 2017.
Poderia verificar e/ou me instruir como usar adequadamente ? 
Ou, o end-point é de teste ? Qual seria o end-point de produção ?

**Comment by Themakew** [comment]
@kazziosoftware, abri uma issue la no repositório dele falando que a API não estava retornando nenhum post, e ele falou: "Por algum motivo o ElasticSearch deu crash e não reiniciou. Já restaurei, porem os posts não foram atualizados no downtime". Acredito que esse seja o motivo.

**Comment by rfischmann** [comment]
@luigifreitas Os posts serão atualizados aos poucos? Se não, há alguma forma de fazermos isso manualmente? Lembro que quando começamos os trabalhos, eu exportei para você o banco de posts do site.

**Comment by luigifreitas** [comment]
@kazziosoftware Fiz uma revisão nos logs do ElasticSearch, descobri que ele ficou fora do ar por quatro dias. Então apenas os posts de quatro dias atras não foram atualizados.
![screenshot 2017-03-28 14 06 53](https://cloud.githubusercontent.com/assets/6627901/24417743/efbd4bf0-13bf-11e7-820c-3f482fc223c5.png)

**Comment by Themakew** [comment]
@luigifreitas, pesquisei App+MacMagazine e me retornou um link de 2012 como primeiro da lista: https://macmagazine.com.br/2012/12/19/%e2%86%aa-poucas-horas-depois-de-lancado-aplicativo-do-macmagazine-assume-1o-lugar-em-downloads-da-categoria-noticias-da-app-store-brasileira/. Ja fiz outras e não retorna em primeiro posts de 2017 q são os mais atuais.

**Comment by luigifreitas** [comment]
@rfischmann Sim, cada vez que um novo post sai, o ElasticSearch é atualizado com ele. Aqueles arquivos serviram para termos todos os posts antigos. Mas na época o serviço era experimental e pode ser que tenha acontecido de algum post escapar. Então, seria bom refazer aquele import manual quando lançarmos a search final.

**Comment by rfischmann** [comment]
@luigifreitas Combinado, então! Vamos testando e desenvolvendo com a base atual e, antes de lançarmos a novidade no app, fazermos de novo uma importação geral e completa para não termos nenhuma dúvida. Fechado. 😃

**Comment by luigifreitas** [comment]
@Themakew Sim, a API retorna dados conforme sai do ElasticSearch. Mas implementar um sort seria rápido. Atualmente o bot faz o sort e envia os dados para o Telegram.

**Comment by luigifreitas** [comment]
@rfischmann Beleza, também fiz uma melhoria, agora ele pega uma thumbnail de cada post para mostrar como preview. Vou finaliza-la e publica-la no [repositório](https://github.com/luigifreitas/macmagazine-elasticsearch-api).

**Comment by rfischmann** [comment]
Show de bola!!

**Comment by rfischmann** [comment]
Pessoal, será que conseguimos implementar isso para a versão 3.2 do app?

**Comment by rfischmann** [comment]
Alguém?…

**Comment by luigifreitas** [comment]
@rfischmann Só precisamos que o recurso da API de buscas seja implementado no Aplicativo. Após disso é só realimentar o servidor com a listas atualizada dos artigos.

**Comment by rfischmann** [comment]
Legal, @luigifreitas! Vamos ver se alguém topa mergulhar nisso.

**Comment by kazziosoftware** [comment]
Feito na versão 4.0
