### ISSUE TITLE
Retorno do recurso de favoritar posts

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#50]
Este foi um recurso que achamos que poderia ser eliminado da nova e recém-lançada versão do app (a 3.0), e que existia até a anterior.

Tínhamos uma "estrelinha" na tela de leitura de posts antes que permitia aos usuários favoritar posts e acessá-los pelo menu lateral (layout antigo, estilo "hambúrguer") do app numa lista personalizada só de posts favoritos.

Tenho minhas dúvidas se isso ainda é algo válido de re-adicionarmos ao app, não temos métricas de uso do recurso nas versões anteriores e se não me engano, pela nova folha de compartilhamento, dá para mandar posts por exemplo para Pockets da vida (serviços de "read it later"). Mas já tiveram, sim, ao menos 1-2 usuários reclamando da ausência dele no novo app.

**Comment by brunoteixeiralc** [comment]
Ou algo do tipo: Ler mais tarde. 
Por exemplo: quando o usuário recebe um notificação poderia ter um botão : **Let mais tarde**
Somente uma sugestão rsrsrs

**Comment by brunoteixeiralc** [comment]
Então no caso teria que ter no aplicativo uma tab nova com o favoritar/ler mais tarde. Certo?

**Comment by rfischmann** [comment]
@brunoteixeiralc Exato, meu caro!

**Comment by rfischmann** [comment]
Toda hora alguém pede isso. 🙃

**Comment by kazziosoftware** [comment]
Feito na versão 4.0
