### ISSUE TITLE
Integração com o 3D Touch de iPhones 6s/6s Plus

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#51]
O app "precisa" ter integração com o **3D Touch** de iPhones 6s/6s Plus.

Não penso em muita utilidade para atalhos no ícone dele — se muito um link direto para o último post publicado, fora isso tenho minhas dúvidas.

Mas o que seria legal, mesmo, é poder dar _Peek & Pop_ nos artigos diretamente pela tela inicial do app (na lista de posts).

Também criei outra _issue_ (#52) sobre podermos tocar e segurar (_tap & hold_) na lista de posts para abrir a folha de compartilhamento.

**Comment by rfischmann** [comment]
A implementação do 3D Touch na lista de posts estará na versão 3.1 do app, a ser lançada nos próximos dias.

Todavia, não irei fechar esta issue ainda pois acho que podemos seguir com mais implementações. O que pensei aqui, de imediato, foi:

- 3D Touch no ícone do app para levar diretamente ao último post publicado. Não consigo pensar em nada mais para isso, ao menos no estado atual do app.

- 3D Touch para preview de links internos de artigos.

Algo mais, pessoal?

**Comment by Themakew** [comment]
@rfischmann a primeira proposta funcionaria, acredito eu, somente quando a pessoa abrisse o app, ou seja, a atualização de último post só se daria depois da pessoa ter aberto o app. Dessa forma seria mais um feature de primeiros post listados.
A segunda já funciona no app.

**Comment by rfischmann** [comment]
Não entendi bem, @Themakew. Você acha a primeira sugestão inviável porque o app primeiro precisa puxar a lista atualizada de posts, é isso?

Caramba, eu nunca tinha testado o 3D Touch em links de artigos. Funciona, mesmo! 😄

**Comment by Themakew** [comment]
@rfischmann não, só quis explicar como funcionaria na prática. Porque deu a entender que você acha que a lista no 3d touch será atualizado com o push do servidor, e não é dessa forma. Já em relação a segunda ideia, por ser uma webview já é nativo. Só temos controle das áreas do app que criamos, com a view da listagem dos post, que teve que ser implementado o peek&pop.

**Comment by rfischmann** [comment]
A lista do 3D Touch não precisaria indicar o título do post em si, poderia ser "Abrir último post publicado" ou algo do tipo. Aí o app abriria, atualizaria a lista e carregaria o último. Rola?

**Comment by Themakew** [comment]
@rfischmann rola sim, na verdade é algo mais fácil de fazer do que eu comentei anteriormente. :)

**Comment by rfischmann** [comment]
Quem pode implementar isso?

**Comment by kazziosoftware** [comment]
@rfischmann não acho que a funcionalidade do 3DTouch para "Abrir o último post publicado" seja muito útil, pq, no fundo, ao abrir o App isso já ocorre.
Seria mais interessante outra função, mas devido às opções atuais do App, não consigo ver nada que possa ser útil de fato.

**Comment by rfischmann** [comment]
Não abre o último post, abre a lista de posts com o último em cima, né? São dois toques.

Concordo que não é nada de extraordinário, mas alguns podem curtir na minha opinião.

**Comment by rfischmann** [comment]
Estará num update liberado esta semana!
