### ISSUE TITLE
Recurso para ampliar imagens dentro de posts

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#54]
Na versão desktop do nosso site, em muitos casos nós linkamos imagens às suas versões em resolução original e indicamos que o leitor pode clicar/tocar na imagem para ampliá-la.

Seria legal o app ter um visualizador nativo para imagens assim, que ao tocadas tomassem a tela inteira (com fundo preto) e permitissem ao usuário dar zoom à vontade.

Se possível, ficaria show se a imagem ampliasse com algum efeito/animação ao ser tocada.

**Comment by Viniciuscarvalho** [comment]
@rfischmann Existe uma lib que uso em um projeto que faz esse efeito de zoom e aumentar a tela quando tocada, `JTSImageInfo`

Se for o caso pode adicionar ao projeto.

**Comment by cesarbars** [comment]
@Viniciuscarvalho A view de detalhe do post é uma `WKWebView`. A `JTSImageInfo` suporta abrir imagens a partir de uma view web? Será que rola a integração com algum evento de toque e ai podemos capturar a imagem?

**Comment by Viniciuscarvalho** [comment]
Creio que sim @cesarbars , o método que faz o zoom na imagem aparentemente pode receber o `WKWebView` e se tiver o parâmetro da imagem pode trabalhar em cima dele e justamente faria esse tap em cima da foto.

O método da biblioteca seria esse, creio eu, é o que estou usando aqui na minha aplicação,

```
@param backgroundStyle Currently, either scaled-and-dimmed, or scaled-dimmed-and-blurred. 
 The latter is like Tweetbot 3.0's background style.
 */
- (instancetype)initWithImageInfo:(JTSImageInfo *)imageInfo
                             mode:(JTSImageViewControllerMode)mode
                  backgroundStyle:(JTSImageViewControllerBackgroundOptions)backgroundOptions;
```

**Comment by Viniciuscarvalho** [comment]
@cesarbars Tem como fazer isso na imagem do `WKWebview`?

```self.imageView.userInteractionEnabled = YES;
        UITapGestureRecognizer * tapPhoto = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(MetodoQueVaiReceberTap)];
        [tapPhoto setNumberOfTapsRequired:1];
        [self.imageView addGestureRecognizer:tapPhoto];```

**Comment by kazziosoftware** [comment]
Atualmente, se tocar e segurar uma imagem no device, aparece uma lista de opções: Salvar, Abrir, Copiar. Acho que isso já resolve, certo ?

**Comment by rfischmann** [comment]
Não. O ideal seria ao tocar numa imagem, ela abrir numa visão tipo a do app Fotos nativo, que permita a pessoa usar o gesto de pinça, girar o aparelho, etc. à vontade. E aí teria um "X" no canto superior direito ou quem sabe só deslizando pro lado ou fazendo pinça para diminuir ela fecharia. Saca?

**Comment by rfischmann** [comment]
[Esse comentário lá no site](https://macmagazine.uol.com.br/post/2020/03/16/tem-update-na-area-do-nosso-app-com-algumas-correcoes-de-bugs/#comment-4835933739) me lembrou desta issue. Será que conseguimos executar no próximo update?

**Comment by Themakew** [comment]
@rfischmann @cassio-rossi Para a implementação dessa feature teria que ter uma implementação específica pela fronteira do site em seu Javascript. Vou colocar um artigo mostrando como seria possível, basicamente teria que ter um disparo do javascript com a url da imagem em alguma parte do site (ideal que seja na própria imagem), dessa forma o app abriria uma nova tela com base nesse link. 

Link do artigo:
https://medium.com/john-lewis-software-engineering/ios-wkwebview-communication-using-javascript-and-swift-ee077e0127eb

**Comment by rfischmann** [comment]
Interessante. Creio que o ideal seria haver um JavaScript no site que só funcionaria quando carregado pelo user-agent do app ("MacMagazine") e seria então automaticamente aplicado a todos os links de imagens. Não me soa como algo complicado.

**Comment by rfischmann** [comment]
Comentário relacionado: https://macmagazine.uol.com.br/post/2020/07/29/pesquisa-airpods-pro-tendem-a-cair-mais-da-orelha-do-que-os-airpods-normais/#comment-5011060602

Acho que precisamos dar prioridade a esta issue.

**Comment by Themakew** [comment]
@rfischmann a parte do javascript já foi implementada?

**Comment by rfischmann** [comment]
Não, alguém teria que desenvolver esse script. Eu não manjo, não. 😉

**Comment by cassio-rossi** [comment]
Posso dar uma olhada e depois dou um parecer.

**Comment by rfischmann** [comment]
Está na versão 4.2, saindo na próxima segunda-feira.
