### ISSUE TITLE
Problema ao logar no Disqus via Facebook

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#55]
Recebemos o relato de um leitor que não consegue se logar no Disqus para comentar usando a sua conta do Facebook: https://d.pr/i/17LoZ

Não chegamos a testar essa possibilidade antes de lançar a versão 3.0 do app, pois todos temos contas nativas no Disqus.

**Comment by Themakew** [comment]
Realmente ocorre o problema, testei aqui e depois que a pessoa preenche os seus dados, fica em uma tela de loading que não sai mais. Por ser ainda uma web view, não consegui identificar o que ocorre. Alguém conseguiu identificar o problema?

**Comment by Themakew** [comment]
@rfischmann Acho q essa issue está resolvida não? Acredito que o único problema agora é que depois que o usuário loga e fica aquelas chaves rodando, entra em um loop infinito que acredito ser problema do Disqus, dado que ocorre em outros apps também. Mas é so retornar a pagina que o login está realizado.

**Comment by rfischmann** [comment]
Na verdade eu nunca tentei/consegui reproduzir o problema, até porque não uso o app para comentar no site. Mas se está funcionando bem e não recebemos novos relatos, acho que está ok mesmo né?

**Comment by Themakew** [comment]
@rfischmann, como comentei o problema que tem é após o login entra uma tela de loading que fica em loop infinito, mas acredito ser problema do próprio Disqus.

**Comment by rfischmann** [comment]
É fácil testar isso: indo diretamente pelo Safari, na versão mobile do site. Se o comportamento for igual, é do Disqus mesmo.

**Comment by Themakew** [comment]
@rfischmann, esse é o porém, porque via web funciona normal, mas mobile não. Tem outros apps que tem esse mesmo comportamento!

**Comment by Themakew** [comment]
@rfischmann Issue resolvida então né?

**Comment by rfischmann** [comment]
Vou fechar até que recebamos novos relatos.

**Comment by rfischmann** [comment]
Estamos recebendo novos relatos desse problema. Ao tentar logar no Disqus via Facebook, aparece apenas uma tela branca.

**Comment by kazziosoftware** [comment]
Fiz alguns testes e parece ser problema do Disqus, que não retorna adequadamente ao ponto certo. Não vejo o que possa ser feito do lado do App - e também parece que só acontece quando o usuário vai se logar pela primeira vez, quando o Disqus pede mais confirmações sobre o uso do serviço.

**Comment by rfischmann** [comment]
Arquivando, ao menos por ora.
