### ISSUE TITLE
Pushes de novos posts duplicados

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#58]
Temos relatos de alguns leitores que estão recebendo _pushes_ duplicados de novos posts, mesmo depois de apagar e reinstalar o app por completo.

Se não me engano, todos estão com a opção de receber _pushes_ para todos os posts ativada.

**Comment by rfischmann** [comment]
Tem muito tempo que ninguém relata isso. @fsaragoca, sabe se foi definitivamente corrigido? Ou seria uma boa deixarmos a issue aberta, esperando pelo menos alguns dias depois da liberação da versão 3.1, que deve movimentar novamente o uso do app?

**Comment by Themakew** [comment]
@rfischmann Essa issue não tem haver com o app, mesmo que ainda esteja acontecendo acho que pode ser fechada.

**Comment by rfischmann** [comment]
É, também tem tempo que ninguém reclama disso.
