### ISSUE TITLE
Modo escuro?

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#60]
Mais de um leitor já pediu que o app incorpore um modo escuro, algo que se fala que poderá vir no iOS 10.

O "problema" é que, para isso ser possível, no mínimo o nosso site teria que ter um modo escuro também de forma a carregar a folha de estilos (CSS) correta pelo acesso mobile via app.

**Comment by cesarbars** [comment]
Seria interessante, provavelmente, adotarmos Milestones para colocar issues 'sugestões' como essas numa fila de backlog futuro.

**Comment by rfischmann** [comment]
De acordo, @cesarbars! Esta issue #60, especificamente, sem dúvida não é para agora.

**Comment by Themakew** [comment]
Há alguma previsão de deixar o app sem a webview e colocar todas as notícias no formato nativo do ios(tableview por exemplo)? Porque daí daria para colocar o modo escuro de forma nativa no ios, mesmo sem ter ainda o modo escuro no ios.

**Comment by rfischmann** [comment]
@Themakew: o app funcionava assim até a versão anterior e tivemos que migrar para o modo _WebView_ para que qualquer mudança no site não requeira também uma atualização "emergencial" no app. O modo responsivo do site já funciona em uns quatro layouts diferentes com os quais temos que nos preocupar a cada mudança, e elas não são tão raras assim.

Acho que a forma mais viável de tornar isso realidade é criando uma folha de estilos (CSS) à parte pro site mesmo em Modo Escuro e colocando um ajuste/botão para ativá-la no app. Quem sabe até oferecer essa opção no layout do site também, para quem quiser.

Mas eu acho que ainda há _issues_ bem mais prioritárias que essa.

**Comment by Themakew** [comment]
@rfischmann da forma como está o app agora, só daria para implementar o modo escuro na tela de listagem dos post, agora na webview a mundança teria que ser html. Creio que essa issue teria que para a equipe do site.

**Comment by rfischmann** [comment]
Sim, acho que teríamos que criar uma segunda folha de estilos (CSS) para transformar o site todo em dark. Vamos deixar isso aqui para futuramente, não vamos fazer isso no nosso layout atual.

**Comment by rfischmann** [comment]
Agora que lançamos o novo layout do site, é perfeitamente possível para mim criar um arquivo CSS à parte com parâmetros para carregar a web view do post com cores escuras.

Eu só não consigo ajustar isso na lista inicial de posts e, obviamente, preciso saber se isso é viável. Penso que a gente incluiria um ajuste no app para ativar o Modo Escuro dele e, com isso ativo, o app automaticamente "chamaria" o arquivo CSS extra no nosso servidor em cima do padrão.

Rola?

**Comment by rfischmann** [comment]
Está vindo na 3.2, em breve.
