### ISSUE TITLE
Travis.ci

### ISSUE THREAD

**Issue by lfarah** [MacMagazine/app-iOS#66]
Devíamos usar o **Travis.ci** para rodar _testes unitários_
[Instruções aqui](https://www.objc.io/issues/6-build-tools/travis-ci/)

**Comment by serralvo** [comment]
In progress

**Comment by Themakew** [comment]
@fsaragoca e @kazziosoftware confirmam a implementação dessa issue?

**Comment by Themakew** [comment]
@kazziosoftware poderia implementar para a versão em swift.

**Comment by kazziosoftware** [comment]
Done e funcionando.

**Comment by Themakew** [comment]
Aconselho a colocar o status da build do Travis no readme:
```
[![Build Status](https://travis-ci.org/MacMagazine/app-iOS.svg?branch=release%2F4.0)](https://travis-ci.org/MacMagazine/app-iOS)
```
