### ISSUE TITLE
Barrinha de erro de conexão aparecendo com muita frequência

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#67]
A barrinha vermelha de erro de conexão tem aparecido com muita frequência aqui, creio que desnecessariamente. Meu palpite é que o app tenta às vezes se atualizar em plano de fundo, não consegue, e aí mesmo horas depois quando abro o app de novo está lá a barrinha no topo (assusta).

**Comment by rfischmann** [comment]
Defini isto como _Blocker_ para o próximo update, acho que é algo simples de resolver e que pessoalmente me irrita bastante.

**Comment by rfischmann** [comment]
Tenho usado bem pouco o app e há tempos não noto isso. Alguém?

**Comment by rfischmann** [comment]
Retiro o que disse, continua na mesma. Isso é péssimo.

**Comment by Themakew** [comment]
@rfischmann  nunca vi essa barrinha de erro quando utilizo o app, ocorre no 3g ou wifi?

**Comment by rfischmann** [comment]
Eu ainda vejo com frequência aqui, mesmo.

**Comment by kazziosoftware** [comment]
Não consigo ver esse problema, mas coloquei um time-out (aonde eu acho que seja o problema) para fazer a mensagem desaparecer depois 0.6s.
Me avisa se resolveu, pq realmente não consigo testar esse problema.

**Comment by rfischmann** [comment]
Vou deixar este aberto só por mais um tempinho enquanto observo o comportamento, ok?

**Comment by Themakew** [comment]
@rfischmann Tem várias issues corrigidas e em aberto ainda, poderia dar uma geral e fechar todas.

**Comment by rfischmann** [comment]
@Themakew Eu estava fazendo justamente isso, hehe. Acabamos de enviar a 3.1.2 pra Apple.

**Comment by rfischmann** [comment]
Acabei de ver ela, mas realmente sumiu mais rápido. A questão é: por que apareceu?

**Comment by michelmelo** [comment]
@rfischmann  eu estou vendo sempre no i7. mesmo com a ultima atualização.

**Comment by michelmelo** [comment]
@kazziosoftware não sei se é isso mais, acontece mais quando estou na rua. nao sei se é pode onde passo que pego varios pontos mortos. e perco acesso e depois da o erro. nao consegue busca mais os feed.

**Comment by Themakew** [comment]
Já vi no log aqui que perde muito fácil mesmo a conexão, mas não vejo essa barrinha. Só vi uma vez ever. @kazziosoftware poderia revisar esse código por completo para encontrar o problema.

**Comment by rfischmann** [comment]
Na minha visão de leigo, é bem fácil corrigir isso: só mostrar o erro se houver uma falha de comunicação com o app ativo/em primeiro plano.

**Comment by Themakew** [comment]
@rfischmann dei uma olhada no código e é basicamente isso que ele faz mesmo, quando abre o app ele busca atualizar os posts, caso não consiga há um disparo de erro, erro esse que dispara esse aviso ao usuário. Só ocorre isso quando o app está aberto, primeiro plano.

**Comment by rfischmann** [comment]
Tem certeza? Pela minha experiência, não é o que acontece. Se o app estiver aberto em segundo plano ele periodicamente tenta atualizar e, se numa dessas não consegue, na próxima vez que eu trago o app para o primeiro plano o erro imediatamente está lá. Só que agora, com o que o @kazziosoftware mexeu, o erro some bem rápido (o que não é nada útil — se for assim, melhor tirar ele de vez).

**Comment by Themakew** [comment]
A parte que analisei é esse o comportamento, foi até onde o @kazziosoftware fez a alteração dele. Aqui no xcode tem vezes que no log aparece erro de conexão, mas o feedback na tela não aparece, realmente não sei o que ocorre sem nem conseguir testar esse comportamento.

**Comment by michelmelo** [comment]
@Themakew no meu caso não aparece sempre, o que me acontece mais é quando recebo um push, e se eu demora ir la ver, aparece essa mensagem.

**Comment by rfischmann** [comment]
Acho que isso é passado, vou arquivar.
