### ISSUE TITLE
Notificações individuais por post?

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#72]
Nos comentários [deste post](https://macmagazine.com.br/2016/08/11/video-aprenda-a-proteger-suas-notas-no-iphone-e-no-mac/), um leitor levantou uma discussão sobre as notificações do app passarem a ser individuais.

Explico: ele quer poder abrir um post pelo _push_ e só liberar aquele post específico do total do _badge_ de notificações do app. Obviamente, para a pessoa limpar tudo ela ou teria que abrir artigo por artigo ou teria que ter algum botão/gesto para isso.

Pessoalmente eu não acho uma boa ideia (posts não são bem como emails, por exemplo), mas queria trazer aqui para discussão. Quem sabe poderia ser um comportamento opcional?

**Comment by rfischmann** [comment]
Aproveitando, recebemos agora uma sugestão sobre as notificações passarem a trazer o conteúdo completo dos posts para quem quiser ler a partir dali já. Pessoalmente, acho isso bem estranho e não creio que seja a função das notificações. O que acham?

**Comment by RaphaelPrata** [comment]
Acredito que não seja uma boa ideia fazer algo que evite que elas entrem no app. Acredito que da forma que está hoje está ok.

**Comment by rfischmann** [comment]
Não entendi, @RaphaelPrata.

**Comment by RaphaelPrata** [comment]
Eu entendi que seria nas notificações do iOS. Colocando a matéria lá às pessoas vão ler e depois limpar a notificação, eu acho. Daí entrariam menos no app e veriam menos propaganda. Desculpe se tiver falando besteira.

**Comment by rfischmann** [comment]
Não é isso. A ideia é soltar um push quando houver uma atualização relevante no post, justamente "chamando" usuários de volta para a matéria.

**Comment by RaphaelPrata** [comment]
Entendi agora. 👍🏼

**Comment by rfischmann** [comment]
Arquivando pois depende do plugin do OneSignal para WordPress.
