### ISSUE TITLE
Integração com o nosso podcast

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#73]
O app merece, futuramente, uma área dedicada ao nosso podcast.

O **Jovem Nerd** lançou [um novo app](https://itunes.apple.com/br/app/jovem-nerd-aplicativo-oficial/id1122679489?mt=8&at=10lt3B) recentemente que faz isso, talvez até de forma mais avançada/completa do que seria suficiente no nosso caso.

Todos os episódios do **MacMagazine no Ar** são [publicados no SoundCloud](https://soundcloud.com/macmagazine), então imagino que deve haver por ele uma forma fácil de fazer essa integração.

**Comment by Themakew** [comment]
Acredito que o app deveria ter todo o seu conteúdo nativo e poderia adicionar a TabBar, porque daí criaria uma Tab só para os podcasts e para futuras features, algo parecido com o app do Jovem Nerd. O q acha?

**Comment by rfischmann** [comment]
Tornar o conteúdo nativo não é uma opção, por ora. Expliquei aqui: https://github.com/madeatsampa/MacMagazine-iOS/issues/60#issuecomment-234714609

Agora, acho que isso independe da implementação de uma área para o podcast.

**Comment by Themakew** [comment]
Em relação ao app ser todo nativo, foi algo que quiz dizer para o futuro mesmo. Quanto a TabBar é uma opção para a feature do podcast, uma tab relacionada só sobre o assunto.

**Comment by teodoro-r** [comment]
Sugeri essa _feature_ numa pesquisa que fizeram no site há algum tempo, não sei se a ideia veio da minha sugestão ou não. Acho que seria muito bom e poderia incrementar muito os podcasts adicionando imagens a qualquer momento, links e etc tal qual o app do Jovem nerd. Além da possibilidade de incluir nativamente a seleção dos assuntos do podcast como foi implementado em 2 ou 3 episódios anteriores.

**Comment by Themakew** [comment]
@rfischmann pelo que pesquisei, a API do soundcloud para cocoa foi descontinuada. Encontrei APIs de terceiros (https://github.com/andresbrun/ABMSoundCloudAPI) e precisa de um Client_id, Secret_key e Redirect_url que pode ser feito por aqui: https://docs.google.com/forms/d/e/1FAIpQLSfNxc82RJuzC0DnISat7n4H-G7IsPQIdaMpe202iiHZEoso9w/formResponse. 

Sinceramente não sei se essa API pode resolver essa issue e nem sei de uma outra forma para que se possa integrar o podcast, @kazziosoftware e @fsaragoca se souberem de uma solução comentem aqui.

**Comment by rfischmann** [comment]
Eu não sei responder quanto à API do SoundCloud, mas vale notar que a integração do app não necessariamente precisa ser via SC. Nós temos um feed XML e uma categoria de posts só do podcast, e se for o caso dá para reproduzir os episódios diretamente pela URL do arquivo MP3 num player próprio do app. É uma alternativa, também.

**Comment by kazziosoftware** [comment]
Feito na versão 4.0

**Comment by Themakew** [comment]
Acredito que essa issue poderia incluir a reprodução do podcast no app nos moldes do Jovem Nerd, ficaria algo nativo e poderia incluir funcionalidades com a do app deles. Fica para discussão.
