### ISSUE TITLE
Notificações de posts atualizados

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#75]
Muitas vezes, quase que diariamente(!), nós atualizamos posts em vez de criar novos e "divulgamos" essas atualizações disparando um _push_ para browsers (Safari, Chrome e Firefox) bem como fazendo um novo post nas redes sociais apontando para a mesma URL — usando a hashtag #atualização.

Quem usa o app não recebe nada disso, então seria interessante bolarmos uma forma de também levar esses _pushes_ para lá.

**Comment by kazziosoftware** [comment]
Provavelmente é algum issue no server e não acredito ser necessário nenhuma modificação no App.

**Comment by rfischmann** [comment]
Não tem nada a ver com o servidor, @kazziosoftware, simplesmente não existe nenhum comando/integração entre atualizações de posts e de _pushes_ do app hoje em dia. É algo que precisamos implementar de alguma forma.

**Comment by Themakew** [comment]
@rfischmann Não estudei muito essa parte de notificação em específico do app do MM e posso estar errado, mas acredito que o @kazziosoftware esteja correto, o servidor que deve disparar a push notification, sendo o iPhone/iPad somente um receiver.

**Comment by rfischmann** [comment]
Sim, isso é fato. Mas a questão é como fazer a coisa funcionar. Tipo, a gente vai ter que ter uma chavinha (_toggle_) dentro da tela de edição de posts no WordPress — ou seja, seria necessário desenvolver um pequeno plugin para isso — para marcarmos quando quisermos disparar um novo _push_ sobre atualizações de posts para usuários do app, tal como hoje fazemos com _pushes_ de navegadores (usamos o [plugin da Pushwoosh](https://wordpress.org/plugins/push-notifications/)). Aí sim, o WordPress enviaria um comando pro servidor de _pushes_ do app. Acho que teria que ser assim…

**Comment by fsaragoca** [comment]
Os pushes iOS são disparados por um app em Rails rodando no Heroku, mas se a gente conseguisse unificar tudo num lugar só seria o ideal.

**Comment by Themakew** [comment]
@fsaragoca, então essa issue fica para se fazer no servidor, 🙃. Já no app, fica a issue #86 relacionada a push notifications.

**Comment by rfischmann** [comment]
Se desse para integrar o sistema de _pushes_ que usamos na Pushwoosh com o app, para nós seria show (que aí controlamos tudo sempre via WordPress). Eu só não sei se é possível…

**Comment by Themakew** [comment]
@rfischmann, fazendo uma rápida pesquisa vi que o pushwoosh tem como sim integrar com ios, android e vários outros. Dê uma pesquisada ai por tutoriais e confirme se procede.

**Comment by rfischmann** [comment]
Que tem coisa sobre iOS lá, tem: http://docs.pushwoosh.com/docs/apns-configuration

Eu só nunca mexi com isso na Pushwoosh e obviamente não saberia nem por onde começar para integrar isso no nosso app.

Atualmente, como falei, só usamos a Pushwoosh para navegadores: Safari, Chrome e Firefox.

**Comment by Themakew** [comment]
Vi essa tuto ai também e está bem detalhada. Agora é so botar a mão na massa 😂

**Comment by unnamedd** [comment]
Se couber uma sugestão de serviço pra APNS: 
https://onesignal.com

**Comment by Themakew** [comment]
Utilizo em outro app e é muito bom mesmo. Não sei se tem como integrar com o WordPress, daí teria que fazer manual. Fica a dica também @rfischmann.

**Comment by rfischmann** [comment]
O ideal mesmo seria fazer isso via Pushwoosh, na qual já temos conta e rodamos um plugin no WordPress.

**Comment by brunoteixeiralc** [comment]
OneSignal é muito bom mesmo! E ele tem integração com a Web. Além de ser de graça.

**Comment by brunoteixeiralc** [comment]
100% gratuito com dashboard completo.

_https://onesignal.com/_

![captura de tela 2018-10-05 as 16 31 36](https://user-images.githubusercontent.com/767993/46556183-372e7b00-c8bc-11e8-930e-884bdfd103fd.png)

**Comment by rfischmann** [comment]
Caramba, deve ter alguma "pegadinha", não é possível hahaha… Vou olhar com calma, muito obrigado.

**Comment by rfischmann** [comment]
@brunoteixeiralc Estamos rodando o site no OneSignal agora! Bom demais. Muito obrigado.

**Comment by brunoteixeiralc** [comment]
Show! @rfischmann .... para push notification na minha opinião ele é o melhor. 🥇

**Comment by rfischmann** [comment]
Será que é fácil integrarmos o OneSignal ao app, substituindo o servidor de _push_ atual dele? Com isso, poderíamos disparar notificações de posts atualizados e matamos esta _issue_.

Eu vi que tem uma opção de adicionar app para iOS lá no painel do OneSignal.

**Comment by unnamedd** [comment]
definitivamente sim, eu fiz um estudo em 2016 dos melhores serviços de APNS e definitivamente o OneSignal foi o melhor de todos, porém, esse ano trabalhando no @evolution-app, eu senti falta de algumas coisas mais customizadas, eu queria usar só umas poucas partes, nesse momento não senti tanta firmeza no SDK deles, então, escrevi o meu próprio backend (em Swift, claro) que integra com a REST API do OneSignal.

**Comment by brunoteixeiralc** [comment]
@rfischmann é possível sim colocar o app no OneSignal e com isso mandar push personalizados direto no dashboard deles ou senão fazer uma integração com o wordpress utilizando o REST API deles.

**Comment by brunoteixeiralc** [comment]
@unnamedd depois compartilha o backend com a gente! 😎

**Comment by unnamedd** [comment]
Well... código aberto!
Fiquem a vontade pra usar. O README está fraquinho ainda, mas tem exemplos práticos.

@brunoteixeiralc, aqui vai alguns links úteis:
- [Uso do Notifications no iOS](https://github.com/Evolution-App/iOS/blob/development/swift-evolution/sourcecode/AppDelegate.swift#L139-L196)
- [**Fixtures**](https://github.com/Evolution-App/Fixtures), responsável por injetar alguns poucos dados no banco. *(Caso decida brincar com esses componentes, é necessário ter instalado o MongoDB e rodar esse projeto antes do Notifications)*
- [**Notifications**](https://github.com/Evolution-App/Notifications), responsável por gerenciar usuários, devices, tags e trackings.

**Comment by rfischmann** [comment]
Bacana!!

**Comment by kazziosoftware** [comment]
Acho que isso já está disponível no plugin do Wordpress para OneSignal, bastando selecionar a opção de Enviar Push quando for salvar um post, seja novo seja atualização.
Acho que esse ticket pode ser fechado.

**Comment by rfischmann** [comment]
@kazziosoftware Sim, é coisa do OneSignal mesmo. O problema é que o plugin deles para WordPress não me permite, na versão atual, personalizar a mensagem de push. Aí é ruim, porque vai o título do post de novo.

**Comment by rfischmann** [comment]
Vou arquivar este, depende do plugin do OneSignal pro WordPress.
