### ISSUE TITLE
Datas sempre em português na lista de posts

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#76]
Atualmente, à medida que vamos rolando a lista de posts na tela inicial do app, ele mostra as datas de dias anteriores a "ontem" no idioma definido pelo iOS.

Aqui, uma screenshot de quando o iOS está em inglês: http://d.pr/i/qyDt

Como o app é todo em português, o ideal é que ele force essas datas também sempre em português. É possível?

**Comment by brunodelgado** [comment]
PR com a alteração enviada. #77

**Comment by kazziosoftware** [comment]
PR aprovada. Correção na branch Development.
Merge ocorrerá após aprovação da nova versão 3.1.1
