### ISSUE TITLE
Evolução da interface para iPad

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#78]
Em breve lançaremos a versão 3.1 do app, que inclui a implementação inicial de suporte a iPad da _issue_ #48.

Como originalmente proposto, ela é bem básica e acho que podemos evoluir a partir daí. Ideias?

**Comment by Themakew** [comment]
A feature da pesquisa seria uma boa tanto para iPad e iPhone.

**Comment by rfischmann** [comment]
@Themakew Você fala sobre a busca de posts, né? Já temos uma _issue_ separada para isso: #49.

**Comment by Themakew** [comment]
@rfischmann sim, então fica um reforço pela implementação da issue #49! :)

**Comment by rfischmann** [comment]
Acabei de pensar em uma coisa, aqui: o post aberto tem que ser identificado como selecionado na coluna lateral esquerda, quem sabe com a célula com fundo azul padrão do iOS.

Além disso, acho que essa célula quando selecionada não deveria ser mais "tocável". Na versão atual, se tocarmos no mesmo post já aberto ele "reabre".

**Comment by Themakew** [comment]
@rfischmann, esses seus "improvements" implementei nesse pull request. 👍

**Comment by rfischmann** [comment]
Show de bola, @Themakew, valeu!! Pelo jeito teremos um update saindo não muito depois da versão 3.1. 😃 Por sinal, já está aguardando aprovação da Apple.

**Comment by rfischmann** [comment]
Mais [uma sugestão](https://macmagazine.com.br/2017/03/27/nosso-app-esta-de-volta-com-tudo-em-sua-versao-3-1-agora-com-suporte-a-ipads-e-ao-3d-touch/#comment-3226739194): suporte à _Split View_ no iPad. Ao menos foi isso que eu entendi.

**Comment by Themakew** [comment]
@rfischmann split view é exatamente o que ja foi implementado no iPad.

**Comment by rfischmann** [comment]
Não é isso, @Themakew. O app tem uma "visão dividida" com uma coluna que lista os posts e outra com a visualização do post em si. O recurso _Split View_ do iOS é o que permite a usuários rodar dois apps lado a lado, algo que o nosso não suporta atualmente. Sacou?

**Comment by Themakew** [comment]
Há sim, é porque no xcode o nome do recurso que falei é split view também. Mas sei sim, estranho que no meu iPad funciona.
![img_0068](https://cloud.githubusercontent.com/assets/3030029/24385313/df76855c-133f-11e7-9ed0-9e4868458f18.PNG)

**Comment by Themakew** [comment]
Testei com a build da app store e está funcionando também, agora o problema do primeiro post ser selecionado automaticamente está prejudicando e muito a utilização do app no split view(issue #81). A correção que fiz ainda seleciona o primeiro post na split view quanto o app abre pela primeira vez, tem que corrigir isso.

**Comment by rfischmann** [comment]
Sorry, @Themakew, que bom que já estamos funcionando com a _Split View_ então! Eu não tinha testado. 😉

**Comment by kazziosoftware** [comment]
Resolvido na v3.1.1
