### ISSUE TITLE
Listas voltam ao topo quando mais artigos são solicitados no final

### ISSUE THREAD

**Issue by sscabral** [MacMagazine/app-iOS#81]
# Bug: Listas voltam ao topo quando mais artigos são solicitados no final
## Sumário
Após chegar ao final da lista de artigos, mais itens podem ser obtidos. Entretanto, ao continuar a rolar a tela para baixá-los, o app retorna a lista ao início. Além disso, o artigo carregado à direta no _split view_ também é recarregado.
## Passos a reproduzir
1. Abrir o app;
2. Selecionar qualquer artigo na lista à esquerda (pode já estar selecionado);
3. Rolar a lista de artigos até o último item carregado;
4. Aguardar o download dos próximos itens
## Resultados esperados
Demais itens devem ser carregados e a posição atual do usuário deve ser mantida em tela, para que ele continue a navegar pela lista a partir dos itens carregados na sequência.
## Resultados atuais
Ao continuar a rolar a tela para baixá-los, o app retorna a lista ao início. Além disso, o artigo carregado à direta no _split view_ também é recarregado.
## Evidência
Gravação em vídeo anexada.
[Uploading Bug-App iOS versão 3.zip…]()
## Versão do sistema operacional
iOS 10.3 Beta 7 - 14E5277a
## Dispositivo
iPad Air 2
## Notas adicionais
Sem maneiras de contornar o problema até o momento.

**Comment by rfischmann** [comment]
Confirmo que também acontece num iPad Pro de 12,9 polegadas rodando o iOS 10.2.1.

**Comment by Themakew** [comment]
@rfischmann @sscabral Implementei um correção para essa issue.

**Comment by kazziosoftware** [comment]
Correção na branch Development

**Comment by Themakew** [comment]
Atualizei minha solução para contemplar o slip view/slide over no iPad. Lembrando que está bastante comprometida a utilização do app em slip view/slide over na atual build 3.1.0, tentem lançar o quanto antes essa correção.

**Comment by Themakew** [comment]
Issue resolvida.
