### ISSUE TITLE
Videos do YouTube não ficam em landscape no iPhone

### ISSUE THREAD

**Issue by Themakew** [MacMagazine/app-iOS#82]
Acredito que por conta do app no iphone não ter landscape mode, os videos quando são reproduzidos não ficam de nenhuma forma em landscape.

**Comment by rfischmann** [comment]
Será que tem como liberar isso **só** para vídeos?

Também seria bom liberar isso quando estivermos com imagens em tela cheia, um recurso sugerido na _issue_ #54.

**Comment by Themakew** [comment]
Tem como sim, o facebook faz isso e outros apps grandes também.

**Comment by kazziosoftware** [comment]
fixed 3.1.2

**Comment by rfischmann** [comment]
Detectei um bug aqui. Quando abrimos um vídeo e colocamos em _landscape_, se sair do vídeo ainda em _landscape_ a barra superior do app fica estranha (perde o alinhamento correto): http://d.pr/i/MYepqC

**Comment by kazziosoftware** [comment]
fixed

**Comment by Themakew** [comment]
O bug de sumir a status bar voltou na última versão do app.
