### ISSUE TITLE
Não é possível trocar de posts após abrir o app via push

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#86]
Relato [obtido via Twitter](https://twitter.com/AlyCWB/status/846781545910276096).

Quando abrimos um post no app via notificação _push_, ao voltar para a lista de posts e tentar selecionar outro, ele sempre abre de volta o artigo original do _push_.

Confirmei aqui.

**Comment by rfischmann** [comment]
Muita gente relatando esse bug, me parece algo realmente grave/chato. Temos que correr com uma correção, pessoal.

**Comment by kazziosoftware** [comment]
Mais detalhes, copiado do Review da AppStore:
O novo app MM (MacMagazine) envia notificações de matérias novas para a central de notificações do iPhone (como sempre foi), o leitor toca para ler uma matéria, lê toda a matéria e depois toca no "botão" VOLTAR lá no topo esquerdo da tela para voltar para as demais matérias do site, escolhe uma próxima matéria para ler e toca pra abrir, mas acontece um bug e a nova matéria não abre, o que abre na verdade é a matéria anterior que você abriu, ou seja, você só consegue abrir uma matéria! Se quiser abrir outra matéria tem de fechar o app e abrir novamente ou olhar pelo navegador mesmo (o que faz com que não seja necessário o app MM)... Já apaguei o app, reiniciei o iPhone e reinstalei-o, mas continua com o mesmo comportamento! Só comigo acontece isso? 🤔😔😰😭 Outro problema que eu já enfrentava no app antigo e continuo com o mesmo problema nessa versão, não consigo ouvir os podcasts naquele "widget" dentro da própria matéria(já que não tenho instalado o app do SoundCloud), eu toco em play, mas o som não sai, nem a barra de progresso do tempo de reprodução muda, enfim, não reproduz

**Comment by kazziosoftware** [comment]
Resolvido na v 3.1.1
