### ISSUE TITLE
Não tem som dentro da própria matéria

### ISSUE THREAD

**Issue by kazziosoftware** [MacMagazine/app-iOS#87]
Copiado de um Review na AppStore:

Outro problema que eu já enfrentava no app antigo e continuo com o mesmo problema nessa versão, não consigo ouvir os podcasts naquele "widget" dentro da própria matéria(já que não tenho instalado o app do SoundCloud), eu toco em play, mas o som não sai, nem a barra de progresso do tempo de reprodução muda, enfim, não reproduz

**Comment by Themakew** [comment]
@kazziosoftware Aqui reproduz normalmente, mas tem q clicar duas vezes para reproduzir.

**Comment by rfischmann** [comment]
É, aqui está rolando também…

**Comment by Themakew** [comment]
@rfischmann  Issue resolvida, acredito que pode ser fechada.
