### ISSUE TITLE
Folha de compartilhamento do Twitter some após alguns segundos

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#89]
Quando usamos a folha de compartilhamento de posts para o **Twitter**, a janelinha dele abre mas some automaticamente após alguns segundos, se não compartilhar rápido.

**Comment by brunodelgado** [comment]
@Themakew Conseguiu testar em um device? Só adicionar a imagem do post como um activity item corrigiu o erro? 🤔
