### ISSUE TITLE
Símbolo de atividade duplicado após login no Disqus via Facebook

### ISSUE THREAD

**Issue by Themakew** [MacMagazine/app-iOS#93]
Depois que fiz o login no facebook para utilizar o disqus, apareceu uma activity duplicada na canto superior esquedo da tela.🤔
![img_0860](https://cloud.githubusercontent.com/assets/3030029/24908928/652e4758-1e98-11e7-82ff-bcc8e13f1ca9.PNG)

**Comment by Themakew** [comment]
O bug ocorre também sempre quando se abre a detail view controller, não somente depois do login.

**Comment by kazziosoftware** [comment]
Fixed na versão 3.1.2
