### ISSUE TITLE
Vídeos do YouTube não ficam em tela cheia no iPad

### ISSUE THREAD

**Issue by Themakew** [MacMagazine/app-iOS#94]
Além disso poderia adicionar a funcionalidade de PiP para iPad.

**Comment by rfischmann** [comment]
Acho que esta _issue_ tem muito a ver com a #82. No iPhone, os vídeos só ficam em modo paisagem (_landscape_) em tela cheia, mesmo.

**Comment by Themakew** [comment]
@rfischmann é parecida, mas diferente. E a issue #82 teoricamente ja foi resolvida no meu pull request, já essa adiciona o enhancement do PiP no iPad.

**Comment by kazziosoftware** [comment]
Esse issue precisa de mais estudo já que está sendo usado iframe no código e as opções são limitadas. O ideal é substituir pelas APIs disponibilizadas pelo Google para videos YouTube no iOS.
Vou verificar a maneira mais fácil de fazer isso, considerando Web+iPhone+iPad e respondo novamente.

**Comment by kazziosoftware** [comment]
Está funcionamento corretamente na versão 4.0 e iOS 12+
