### ISSUE TITLE
Crash ao tentar salvar imagens em posts

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#95]
Relato de leitor:

> Está acontecendo um fechamento inesperado no aplicativo MacMagazine, quando fui no post sobre o smartphone que o criador do Android está fazendo, fui tentar fazer download da imagem do aparelho segurando com dedo encima da imagem até aparecer a mensagem de salvar a imagem, mas quando faço isso o aplicativo da uma congelada e logo em seguida fecha sem salvar a imagem. iPhone 6 de 64GB, iOS 10.3.2

Confirmei aqui no meu.

**Comment by kazziosoftware** [comment]
Fixed na versão 3.1.2
