### ISSUE TITLE
Botão de posts mais atuais na tela principal

### ISSUE THREAD

**Issue by Themakew** [MacMagazine/app-iOS#97]
A ideia é fazer algo como vários apps com timeline fazem, como por exemplo o twitter:
![fullsizerender 2](https://user-images.githubusercontent.com/3030029/26878715-d52a7b64-4b64-11e7-9048-fd749e51cb0d.jpg)

E assim que o usuário clicar, a tableview subir para os posts mais atuais.

**Comment by rfischmann** [comment]
Mas isso faz mais sentido quanto a timeline atualiza com muita frequência, não? No nosso caso, o cara abre o app para ler um ou alguns posts e fecha. Teria que coincidir de, no momento em que ele está rolando a lista, sair um post novo.

**Comment by Themakew** [comment]
Abri o app hoje, e como ele já estava em background, a tableview ficou nos posts de ontem. Ai a activity rodou, atualizou com novos posts e não tive nenhum feedback visual. Falta esse feedback que viria por esse botão.

**Comment by Themakew** [comment]
Ou faz que nem o Instagram que sempre sobe toda a tableview independente quando ocorre a atualização do conteúdo.

**Comment by rfischmann** [comment]
Aí faz sentido!

**Comment by Themakew** [comment]
No meu último pull request optei pela segunda implementação, onde ocorre a atualização e a tableview sobe automaticamente.

**Comment by rfischmann** [comment]
Fechado!
