### ISSUE TITLE
Crash ao tentar compartilhar imagem

### ISSUE THREAD

**Issue by rfischmann** [MacMagazine/app-iOS#98]
Um leitor nos avisou sobre um crash na versão atual, confirmei aqui.

Em posts com imagens que podem ser clicadas/tocadas, [como este aqui](https://macmagazine.com.br/2017/06/06/voces-pediram-aqui-estao-os-novos-wallpapers-do-ios-11-do-macos-high-sierra-10-13/), na visão de imagem, ao tocar no ícone de compartilhamento o app fecha na hora.

Talvez seria o caso de só esconder esse ícone na visão de imagem? Aliás, por mim sumia a interface toda do app e deixava a imagem centralizada na tela sobre um fundo preto. Rola?

**Comment by Themakew** [comment]
@rfischmann realmente essa nova tela quebra o tracking do código, até o meu último pull request tive que fechar por ser bastante afetado, gerando assim vários bugs. @kazziosoftware vc sabe me dizer onde ocorre a criação desta tela no código?

**Comment by Themakew** [comment]
@rfischmann já resolvi essa issue, muito simples na verdade. Acredito que não há necessidade de tirar o button de share.

**Comment by rfischmann** [comment]
Então tá! 😉

**Comment by Themakew** [comment]
@rfischmann só para você entender, o botão share é bastante útil nesta tela ainda pelo fato de precisar de dois cliques para mandar a imagem, no caso, para outro lugar. Sem ele é preciso mandar para o fotos e de lá fazer o compartilhamento, chato não? 🤔

**Comment by rfischmann** [comment]
Entendi, faz sentido, mas ao mesmo tempo compartilhar imagens não é um recurso-base do nosso app.

Eu preferiria que imagens nesse caso abrissem numa visão em tela cheia similar à do app Fotos nativo. E dá até para manter a barrinha superior ao tocar, com a função de compartilhamento.

**Comment by Themakew** [comment]
@rfischmann uma coisa não anula a outra. Agora o que não entendi foi em relação a abrir igual o fotos, comparei um ao outro e o app já abre a imagem em tela cheia, dá para dar zoom e compartilhar. Você se refere a algum outro recurso?

**Comment by rfischmann** [comment]
O que falta é ela ficar centralizada verticalmente e, com um toque, toda a interface sumir (tudo em volta da foto ficar preto). Saca?

**Comment by Themakew** [comment]
@rfischmann ah sim, uma boa issue para submeter! 🙃

**Comment by rfischmann** [comment]
É basicamente o que sugeri na issue #54.

**Comment by kazziosoftware** [comment]
Acho que é o mesmo issue #103, confere?

**Comment by rfischmann** [comment]
Sim, o _issue_ tinha sido resolvido e voltou. Concluindo aqui.
