### ISSUE TITLE
Bug no modo splitview iPad 

### ISSUE THREAD

**Issue by Themakew** [MacMagazine/app-iOS#99]
Quando se está em splitview e se abre um post, quando volta para a tela de posts e clica no mesmo post anteriormente aberto, o post não abre. A tableview cell fica somente selecionada mas não abre.

**Comment by kazziosoftware** [comment]
Acredito q este bug não exista pois o splitview fica sempre "aberto", não sendo possível "voltar para a tela de post anteriormente aberta".

**Comment by Themakew** [comment]
Esse bug acontece direto, faz um teste ai. O que eu disse em voltar para tela de posts foi em relação ao clique do usuário e a atenção voltada para a parte da splitview que tem os posts.

**Comment by kazziosoftware** [comment]
Por favor @Themakew poderia detalhar o problema e o passo-a-passo para conseguir reproduzir o problema? Se possível, inclua um video reproduzindo o problema. Grato.

**Comment by Themakew** [comment]
Como tem tempo que não uso o app, o problema descrito acredito que foi corrido. O único bug que pesiste é a perda do tracking de qual post está aberto após o app ir para background.
Como aqui não aceita videos, a segunda foto é a do app voltado de background:
![3783504f-fe53-43f7-a928-3209c092b875](https://user-images.githubusercontent.com/3030029/34041414-2329c6b6-e17f-11e7-8939-37b9bfa112ab.png)
![0044019b-ab9f-4a33-ac7c-5bc9afd10f87](https://user-images.githubusercontent.com/3030029/34041416-23ad4536-e17f-11e7-9b33-d7e9e8c8b1ec.png)

**Comment by kazziosoftware** [comment]
@Themakew foi o que achei, q já tinha sido corrigido. A "persistência" da seleção foi corrigida na v 3.1.5.

**Comment by Themakew** [comment]
O erro que mostrei nas imagens ainda pesiste.

**Comment by rfischmann** [comment]
Ué, @Themakew, o @kazziosoftware disse que será corrigido na 3.1.5. Você não testou ela ainda.

**Comment by Themakew** [comment]
Acredito que ele se referiu ao erro falado no primeiro comment não @rfischmann? Caso o erros mostrado nas imagens também tenha sido corrigido então desconsidere meu comentário anterior.

**Comment by Themakew** [comment]
Outro bug relacionado a seleção da tableview, nessa foto abaixo eu abri o app, a seleção da primeira row da tableview ocorreu e logo depois sumiu, tirou a seleção da row sozinho o app. Dessa forma o tranking do post que está aberto foi perdido:

![fe7018c8-3307-497c-ab98-e24604690ef7](https://user-images.githubusercontent.com/3030029/34328123-0212d18a-e8bd-11e7-86a9-5df92975224f.png)

**Comment by kazziosoftware** [comment]
@rfischmann acho q este bug já foi corrigido. Caso alguém comente sobre ele, voltamos a abrir. O que acha?

**Comment by rfischmann** [comment]
De acordo.

**Comment by rfischmann** [comment]
Confirmo aqui. Realmente, dá para melhorar isso.

**Comment by kazziosoftware** [comment]
Feito na versão 4.0
